// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: visionapi/aic.proto
// Protobuf Java Version: 4.26.0

package de.starwit.visionapi;

public final class Aic {
  private Aic() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 0,
      /* suffix= */ "",
      Aic.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AiCockpitMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:visionapi.AiCockpitMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint64 timestamp_utc_ms = 1;</code>
     * @return The timestampUtcMs.
     */
    long getTimestampUtcMs();

    /**
     * <code>string media_url = 2;</code>
     * @return The mediaUrl.
     */
    java.lang.String getMediaUrl();
    /**
     * <code>string media_url = 2;</code>
     * @return The bytes for mediaUrl.
     */
    com.google.protobuf.ByteString
        getMediaUrlBytes();

    /**
     * <code>.visionapi.ModelInfo model_info = 3;</code>
     * @return Whether the modelInfo field is set.
     */
    boolean hasModelInfo();
    /**
     * <code>.visionapi.ModelInfo model_info = 3;</code>
     * @return The modelInfo.
     */
    de.starwit.visionapi.Common.ModelInfo getModelInfo();
    /**
     * <code>.visionapi.ModelInfo model_info = 3;</code>
     */
    de.starwit.visionapi.Common.ModelInfoOrBuilder getModelInfoOrBuilder();
  }
  /**
   * Protobuf type {@code visionapi.AiCockpitMessage}
   */
  public static final class AiCockpitMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:visionapi.AiCockpitMessage)
      AiCockpitMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 26,
        /* patch= */ 0,
        /* suffix= */ "",
        AiCockpitMessage.class.getName());
    }
    // Use AiCockpitMessage.newBuilder() to construct.
    private AiCockpitMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private AiCockpitMessage() {
      mediaUrl_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return de.starwit.visionapi.Aic.internal_static_visionapi_AiCockpitMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return de.starwit.visionapi.Aic.internal_static_visionapi_AiCockpitMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              de.starwit.visionapi.Aic.AiCockpitMessage.class, de.starwit.visionapi.Aic.AiCockpitMessage.Builder.class);
    }

    private int bitField0_;
    public static final int TIMESTAMP_UTC_MS_FIELD_NUMBER = 1;
    private long timestampUtcMs_ = 0L;
    /**
     * <code>uint64 timestamp_utc_ms = 1;</code>
     * @return The timestampUtcMs.
     */
    @java.lang.Override
    public long getTimestampUtcMs() {
      return timestampUtcMs_;
    }

    public static final int MEDIA_URL_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object mediaUrl_ = "";
    /**
     * <code>string media_url = 2;</code>
     * @return The mediaUrl.
     */
    @java.lang.Override
    public java.lang.String getMediaUrl() {
      java.lang.Object ref = mediaUrl_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        mediaUrl_ = s;
        return s;
      }
    }
    /**
     * <code>string media_url = 2;</code>
     * @return The bytes for mediaUrl.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMediaUrlBytes() {
      java.lang.Object ref = mediaUrl_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mediaUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MODEL_INFO_FIELD_NUMBER = 3;
    private de.starwit.visionapi.Common.ModelInfo modelInfo_;
    /**
     * <code>.visionapi.ModelInfo model_info = 3;</code>
     * @return Whether the modelInfo field is set.
     */
    @java.lang.Override
    public boolean hasModelInfo() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.visionapi.ModelInfo model_info = 3;</code>
     * @return The modelInfo.
     */
    @java.lang.Override
    public de.starwit.visionapi.Common.ModelInfo getModelInfo() {
      return modelInfo_ == null ? de.starwit.visionapi.Common.ModelInfo.getDefaultInstance() : modelInfo_;
    }
    /**
     * <code>.visionapi.ModelInfo model_info = 3;</code>
     */
    @java.lang.Override
    public de.starwit.visionapi.Common.ModelInfoOrBuilder getModelInfoOrBuilder() {
      return modelInfo_ == null ? de.starwit.visionapi.Common.ModelInfo.getDefaultInstance() : modelInfo_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (timestampUtcMs_ != 0L) {
        output.writeUInt64(1, timestampUtcMs_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(mediaUrl_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, mediaUrl_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(3, getModelInfo());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (timestampUtcMs_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, timestampUtcMs_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(mediaUrl_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, mediaUrl_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getModelInfo());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof de.starwit.visionapi.Aic.AiCockpitMessage)) {
        return super.equals(obj);
      }
      de.starwit.visionapi.Aic.AiCockpitMessage other = (de.starwit.visionapi.Aic.AiCockpitMessage) obj;

      if (getTimestampUtcMs()
          != other.getTimestampUtcMs()) return false;
      if (!getMediaUrl()
          .equals(other.getMediaUrl())) return false;
      if (hasModelInfo() != other.hasModelInfo()) return false;
      if (hasModelInfo()) {
        if (!getModelInfo()
            .equals(other.getModelInfo())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TIMESTAMP_UTC_MS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimestampUtcMs());
      hash = (37 * hash) + MEDIA_URL_FIELD_NUMBER;
      hash = (53 * hash) + getMediaUrl().hashCode();
      if (hasModelInfo()) {
        hash = (37 * hash) + MODEL_INFO_FIELD_NUMBER;
        hash = (53 * hash) + getModelInfo().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static de.starwit.visionapi.Aic.AiCockpitMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.starwit.visionapi.Aic.AiCockpitMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.starwit.visionapi.Aic.AiCockpitMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.starwit.visionapi.Aic.AiCockpitMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.starwit.visionapi.Aic.AiCockpitMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.starwit.visionapi.Aic.AiCockpitMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.starwit.visionapi.Aic.AiCockpitMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static de.starwit.visionapi.Aic.AiCockpitMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static de.starwit.visionapi.Aic.AiCockpitMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static de.starwit.visionapi.Aic.AiCockpitMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static de.starwit.visionapi.Aic.AiCockpitMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static de.starwit.visionapi.Aic.AiCockpitMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(de.starwit.visionapi.Aic.AiCockpitMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code visionapi.AiCockpitMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:visionapi.AiCockpitMessage)
        de.starwit.visionapi.Aic.AiCockpitMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return de.starwit.visionapi.Aic.internal_static_visionapi_AiCockpitMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return de.starwit.visionapi.Aic.internal_static_visionapi_AiCockpitMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                de.starwit.visionapi.Aic.AiCockpitMessage.class, de.starwit.visionapi.Aic.AiCockpitMessage.Builder.class);
      }

      // Construct using de.starwit.visionapi.Aic.AiCockpitMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage
                .alwaysUseFieldBuilders) {
          getModelInfoFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        timestampUtcMs_ = 0L;
        mediaUrl_ = "";
        modelInfo_ = null;
        if (modelInfoBuilder_ != null) {
          modelInfoBuilder_.dispose();
          modelInfoBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return de.starwit.visionapi.Aic.internal_static_visionapi_AiCockpitMessage_descriptor;
      }

      @java.lang.Override
      public de.starwit.visionapi.Aic.AiCockpitMessage getDefaultInstanceForType() {
        return de.starwit.visionapi.Aic.AiCockpitMessage.getDefaultInstance();
      }

      @java.lang.Override
      public de.starwit.visionapi.Aic.AiCockpitMessage build() {
        de.starwit.visionapi.Aic.AiCockpitMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public de.starwit.visionapi.Aic.AiCockpitMessage buildPartial() {
        de.starwit.visionapi.Aic.AiCockpitMessage result = new de.starwit.visionapi.Aic.AiCockpitMessage(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(de.starwit.visionapi.Aic.AiCockpitMessage result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.timestampUtcMs_ = timestampUtcMs_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.mediaUrl_ = mediaUrl_;
        }
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.modelInfo_ = modelInfoBuilder_ == null
              ? modelInfo_
              : modelInfoBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof de.starwit.visionapi.Aic.AiCockpitMessage) {
          return mergeFrom((de.starwit.visionapi.Aic.AiCockpitMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(de.starwit.visionapi.Aic.AiCockpitMessage other) {
        if (other == de.starwit.visionapi.Aic.AiCockpitMessage.getDefaultInstance()) return this;
        if (other.getTimestampUtcMs() != 0L) {
          setTimestampUtcMs(other.getTimestampUtcMs());
        }
        if (!other.getMediaUrl().isEmpty()) {
          mediaUrl_ = other.mediaUrl_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.hasModelInfo()) {
          mergeModelInfo(other.getModelInfo());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                timestampUtcMs_ = input.readUInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                mediaUrl_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                input.readMessage(
                    getModelInfoFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long timestampUtcMs_ ;
      /**
       * <code>uint64 timestamp_utc_ms = 1;</code>
       * @return The timestampUtcMs.
       */
      @java.lang.Override
      public long getTimestampUtcMs() {
        return timestampUtcMs_;
      }
      /**
       * <code>uint64 timestamp_utc_ms = 1;</code>
       * @param value The timestampUtcMs to set.
       * @return This builder for chaining.
       */
      public Builder setTimestampUtcMs(long value) {

        timestampUtcMs_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 timestamp_utc_ms = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimestampUtcMs() {
        bitField0_ = (bitField0_ & ~0x00000001);
        timestampUtcMs_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object mediaUrl_ = "";
      /**
       * <code>string media_url = 2;</code>
       * @return The mediaUrl.
       */
      public java.lang.String getMediaUrl() {
        java.lang.Object ref = mediaUrl_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          mediaUrl_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string media_url = 2;</code>
       * @return The bytes for mediaUrl.
       */
      public com.google.protobuf.ByteString
          getMediaUrlBytes() {
        java.lang.Object ref = mediaUrl_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          mediaUrl_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string media_url = 2;</code>
       * @param value The mediaUrl to set.
       * @return This builder for chaining.
       */
      public Builder setMediaUrl(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        mediaUrl_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string media_url = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMediaUrl() {
        mediaUrl_ = getDefaultInstance().getMediaUrl();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string media_url = 2;</code>
       * @param value The bytes for mediaUrl to set.
       * @return This builder for chaining.
       */
      public Builder setMediaUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        mediaUrl_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private de.starwit.visionapi.Common.ModelInfo modelInfo_;
      private com.google.protobuf.SingleFieldBuilder<
          de.starwit.visionapi.Common.ModelInfo, de.starwit.visionapi.Common.ModelInfo.Builder, de.starwit.visionapi.Common.ModelInfoOrBuilder> modelInfoBuilder_;
      /**
       * <code>.visionapi.ModelInfo model_info = 3;</code>
       * @return Whether the modelInfo field is set.
       */
      public boolean hasModelInfo() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>.visionapi.ModelInfo model_info = 3;</code>
       * @return The modelInfo.
       */
      public de.starwit.visionapi.Common.ModelInfo getModelInfo() {
        if (modelInfoBuilder_ == null) {
          return modelInfo_ == null ? de.starwit.visionapi.Common.ModelInfo.getDefaultInstance() : modelInfo_;
        } else {
          return modelInfoBuilder_.getMessage();
        }
      }
      /**
       * <code>.visionapi.ModelInfo model_info = 3;</code>
       */
      public Builder setModelInfo(de.starwit.visionapi.Common.ModelInfo value) {
        if (modelInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          modelInfo_ = value;
        } else {
          modelInfoBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>.visionapi.ModelInfo model_info = 3;</code>
       */
      public Builder setModelInfo(
          de.starwit.visionapi.Common.ModelInfo.Builder builderForValue) {
        if (modelInfoBuilder_ == null) {
          modelInfo_ = builderForValue.build();
        } else {
          modelInfoBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>.visionapi.ModelInfo model_info = 3;</code>
       */
      public Builder mergeModelInfo(de.starwit.visionapi.Common.ModelInfo value) {
        if (modelInfoBuilder_ == null) {
          if (((bitField0_ & 0x00000004) != 0) &&
            modelInfo_ != null &&
            modelInfo_ != de.starwit.visionapi.Common.ModelInfo.getDefaultInstance()) {
            getModelInfoBuilder().mergeFrom(value);
          } else {
            modelInfo_ = value;
          }
        } else {
          modelInfoBuilder_.mergeFrom(value);
        }
        if (modelInfo_ != null) {
          bitField0_ |= 0x00000004;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.visionapi.ModelInfo model_info = 3;</code>
       */
      public Builder clearModelInfo() {
        bitField0_ = (bitField0_ & ~0x00000004);
        modelInfo_ = null;
        if (modelInfoBuilder_ != null) {
          modelInfoBuilder_.dispose();
          modelInfoBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.visionapi.ModelInfo model_info = 3;</code>
       */
      public de.starwit.visionapi.Common.ModelInfo.Builder getModelInfoBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getModelInfoFieldBuilder().getBuilder();
      }
      /**
       * <code>.visionapi.ModelInfo model_info = 3;</code>
       */
      public de.starwit.visionapi.Common.ModelInfoOrBuilder getModelInfoOrBuilder() {
        if (modelInfoBuilder_ != null) {
          return modelInfoBuilder_.getMessageOrBuilder();
        } else {
          return modelInfo_ == null ?
              de.starwit.visionapi.Common.ModelInfo.getDefaultInstance() : modelInfo_;
        }
      }
      /**
       * <code>.visionapi.ModelInfo model_info = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          de.starwit.visionapi.Common.ModelInfo, de.starwit.visionapi.Common.ModelInfo.Builder, de.starwit.visionapi.Common.ModelInfoOrBuilder> 
          getModelInfoFieldBuilder() {
        if (modelInfoBuilder_ == null) {
          modelInfoBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              de.starwit.visionapi.Common.ModelInfo, de.starwit.visionapi.Common.ModelInfo.Builder, de.starwit.visionapi.Common.ModelInfoOrBuilder>(
                  getModelInfo(),
                  getParentForChildren(),
                  isClean());
          modelInfo_ = null;
        }
        return modelInfoBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:visionapi.AiCockpitMessage)
    }

    // @@protoc_insertion_point(class_scope:visionapi.AiCockpitMessage)
    private static final de.starwit.visionapi.Aic.AiCockpitMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new de.starwit.visionapi.Aic.AiCockpitMessage();
    }

    public static de.starwit.visionapi.Aic.AiCockpitMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AiCockpitMessage>
        PARSER = new com.google.protobuf.AbstractParser<AiCockpitMessage>() {
      @java.lang.Override
      public AiCockpitMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<AiCockpitMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AiCockpitMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public de.starwit.visionapi.Aic.AiCockpitMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_visionapi_AiCockpitMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_visionapi_AiCockpitMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023visionapi/aic.proto\022\tvisionapi\032\026vision" +
      "api/common.proto\"i\n\020AiCockpitMessage\022\030\n\020" +
      "timestamp_utc_ms\030\001 \001(\004\022\021\n\tmedia_url\030\002 \001(" +
      "\t\022(\n\nmodel_info\030\003 \001(\0132\024.visionapi.ModelI" +
      "nfoB\026\n\024de.starwit.visionapib\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          de.starwit.visionapi.Common.getDescriptor(),
        });
    internal_static_visionapi_AiCockpitMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_visionapi_AiCockpitMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_visionapi_AiCockpitMessage_descriptor,
        new java.lang.String[] { "TimestampUtcMs", "MediaUrl", "ModelInfo", });
    descriptor.resolveAllFeaturesImmutable();
    de.starwit.visionapi.Common.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
