// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: visionapi/analytics.proto
// Protobuf Java Version: 4.31.1

package de.starwit.visionapi;

@com.google.protobuf.Generated
public final class Analytics {
  private Analytics() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 31,
      /* patch= */ 1,
      /* suffix= */ "",
      Analytics.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DetectionCountMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:visionapi.DetectionCountMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Zeitpunkt der Message-Erstellung, Zeitintervall wird in der Komponenten eingestellt
     * </pre>
     *
     * <code>uint64 timestamp_utc_ms = 1;</code>
     * @return The timestampUtcMs.
     */
    long getTimestampUtcMs();

    /**
     * <code>repeated .visionapi.DetectionCount detection_counts = 2;</code>
     */
    java.util.List<de.starwit.visionapi.Analytics.DetectionCount> 
        getDetectionCountsList();
    /**
     * <code>repeated .visionapi.DetectionCount detection_counts = 2;</code>
     */
    de.starwit.visionapi.Analytics.DetectionCount getDetectionCounts(int index);
    /**
     * <code>repeated .visionapi.DetectionCount detection_counts = 2;</code>
     */
    int getDetectionCountsCount();
    /**
     * <code>repeated .visionapi.DetectionCount detection_counts = 2;</code>
     */
    java.util.List<? extends de.starwit.visionapi.Analytics.DetectionCountOrBuilder> 
        getDetectionCountsOrBuilderList();
    /**
     * <code>repeated .visionapi.DetectionCount detection_counts = 2;</code>
     */
    de.starwit.visionapi.Analytics.DetectionCountOrBuilder getDetectionCountsOrBuilder(
        int index);

    /**
     * <code>bytes sae_uuid = 4;</code>
     * @return The saeUuid.
     */
    com.google.protobuf.ByteString getSaeUuid();

    /**
     * <code>.visionapi.MessageType type = 1000;</code>
     * @return The enum numeric value on the wire for type.
     */
    int getTypeValue();
    /**
     * <code>.visionapi.MessageType type = 1000;</code>
     * @return The type.
     */
    de.starwit.visionapi.Common.MessageType getType();
  }
  /**
   * Protobuf type {@code visionapi.DetectionCountMessage}
   */
  public static final class DetectionCountMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:visionapi.DetectionCountMessage)
      DetectionCountMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 31,
        /* patch= */ 1,
        /* suffix= */ "",
        DetectionCountMessage.class.getName());
    }
    // Use DetectionCountMessage.newBuilder() to construct.
    private DetectionCountMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private DetectionCountMessage() {
      detectionCounts_ = java.util.Collections.emptyList();
      saeUuid_ = com.google.protobuf.ByteString.EMPTY;
      type_ = 0;
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return de.starwit.visionapi.Analytics.internal_static_visionapi_DetectionCountMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return de.starwit.visionapi.Analytics.internal_static_visionapi_DetectionCountMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              de.starwit.visionapi.Analytics.DetectionCountMessage.class, de.starwit.visionapi.Analytics.DetectionCountMessage.Builder.class);
    }

    public static final int TIMESTAMP_UTC_MS_FIELD_NUMBER = 1;
    private long timestampUtcMs_ = 0L;
    /**
     * <pre>
     * Zeitpunkt der Message-Erstellung, Zeitintervall wird in der Komponenten eingestellt
     * </pre>
     *
     * <code>uint64 timestamp_utc_ms = 1;</code>
     * @return The timestampUtcMs.
     */
    @java.lang.Override
    public long getTimestampUtcMs() {
      return timestampUtcMs_;
    }

    public static final int DETECTION_COUNTS_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private java.util.List<de.starwit.visionapi.Analytics.DetectionCount> detectionCounts_;
    /**
     * <code>repeated .visionapi.DetectionCount detection_counts = 2;</code>
     */
    @java.lang.Override
    public java.util.List<de.starwit.visionapi.Analytics.DetectionCount> getDetectionCountsList() {
      return detectionCounts_;
    }
    /**
     * <code>repeated .visionapi.DetectionCount detection_counts = 2;</code>
     */
    @java.lang.Override
    public java.util.List<? extends de.starwit.visionapi.Analytics.DetectionCountOrBuilder> 
        getDetectionCountsOrBuilderList() {
      return detectionCounts_;
    }
    /**
     * <code>repeated .visionapi.DetectionCount detection_counts = 2;</code>
     */
    @java.lang.Override
    public int getDetectionCountsCount() {
      return detectionCounts_.size();
    }
    /**
     * <code>repeated .visionapi.DetectionCount detection_counts = 2;</code>
     */
    @java.lang.Override
    public de.starwit.visionapi.Analytics.DetectionCount getDetectionCounts(int index) {
      return detectionCounts_.get(index);
    }
    /**
     * <code>repeated .visionapi.DetectionCount detection_counts = 2;</code>
     */
    @java.lang.Override
    public de.starwit.visionapi.Analytics.DetectionCountOrBuilder getDetectionCountsOrBuilder(
        int index) {
      return detectionCounts_.get(index);
    }

    public static final int SAE_UUID_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString saeUuid_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes sae_uuid = 4;</code>
     * @return The saeUuid.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getSaeUuid() {
      return saeUuid_;
    }

    public static final int TYPE_FIELD_NUMBER = 1000;
    private int type_ = 0;
    /**
     * <code>.visionapi.MessageType type = 1000;</code>
     * @return The enum numeric value on the wire for type.
     */
    @java.lang.Override public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.visionapi.MessageType type = 1000;</code>
     * @return The type.
     */
    @java.lang.Override public de.starwit.visionapi.Common.MessageType getType() {
      de.starwit.visionapi.Common.MessageType result = de.starwit.visionapi.Common.MessageType.forNumber(type_);
      return result == null ? de.starwit.visionapi.Common.MessageType.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (timestampUtcMs_ != 0L) {
        output.writeUInt64(1, timestampUtcMs_);
      }
      for (int i = 0; i < detectionCounts_.size(); i++) {
        output.writeMessage(2, detectionCounts_.get(i));
      }
      if (!saeUuid_.isEmpty()) {
        output.writeBytes(4, saeUuid_);
      }
      if (type_ != de.starwit.visionapi.Common.MessageType.UNSPECIFIED.getNumber()) {
        output.writeEnum(1000, type_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (timestampUtcMs_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, timestampUtcMs_);
      }
      for (int i = 0; i < detectionCounts_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, detectionCounts_.get(i));
      }
      if (!saeUuid_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, saeUuid_);
      }
      if (type_ != de.starwit.visionapi.Common.MessageType.UNSPECIFIED.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1000, type_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof de.starwit.visionapi.Analytics.DetectionCountMessage)) {
        return super.equals(obj);
      }
      de.starwit.visionapi.Analytics.DetectionCountMessage other = (de.starwit.visionapi.Analytics.DetectionCountMessage) obj;

      if (getTimestampUtcMs()
          != other.getTimestampUtcMs()) return false;
      if (!getDetectionCountsList()
          .equals(other.getDetectionCountsList())) return false;
      if (!getSaeUuid()
          .equals(other.getSaeUuid())) return false;
      if (type_ != other.type_) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TIMESTAMP_UTC_MS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimestampUtcMs());
      if (getDetectionCountsCount() > 0) {
        hash = (37 * hash) + DETECTION_COUNTS_FIELD_NUMBER;
        hash = (53 * hash) + getDetectionCountsList().hashCode();
      }
      hash = (37 * hash) + SAE_UUID_FIELD_NUMBER;
      hash = (53 * hash) + getSaeUuid().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static de.starwit.visionapi.Analytics.DetectionCountMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.starwit.visionapi.Analytics.DetectionCountMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.starwit.visionapi.Analytics.DetectionCountMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.starwit.visionapi.Analytics.DetectionCountMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.starwit.visionapi.Analytics.DetectionCountMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.starwit.visionapi.Analytics.DetectionCountMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.starwit.visionapi.Analytics.DetectionCountMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static de.starwit.visionapi.Analytics.DetectionCountMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static de.starwit.visionapi.Analytics.DetectionCountMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static de.starwit.visionapi.Analytics.DetectionCountMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static de.starwit.visionapi.Analytics.DetectionCountMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static de.starwit.visionapi.Analytics.DetectionCountMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(de.starwit.visionapi.Analytics.DetectionCountMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code visionapi.DetectionCountMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:visionapi.DetectionCountMessage)
        de.starwit.visionapi.Analytics.DetectionCountMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return de.starwit.visionapi.Analytics.internal_static_visionapi_DetectionCountMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return de.starwit.visionapi.Analytics.internal_static_visionapi_DetectionCountMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                de.starwit.visionapi.Analytics.DetectionCountMessage.class, de.starwit.visionapi.Analytics.DetectionCountMessage.Builder.class);
      }

      // Construct using de.starwit.visionapi.Analytics.DetectionCountMessage.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        timestampUtcMs_ = 0L;
        if (detectionCountsBuilder_ == null) {
          detectionCounts_ = java.util.Collections.emptyList();
        } else {
          detectionCounts_ = null;
          detectionCountsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        saeUuid_ = com.google.protobuf.ByteString.EMPTY;
        type_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return de.starwit.visionapi.Analytics.internal_static_visionapi_DetectionCountMessage_descriptor;
      }

      @java.lang.Override
      public de.starwit.visionapi.Analytics.DetectionCountMessage getDefaultInstanceForType() {
        return de.starwit.visionapi.Analytics.DetectionCountMessage.getDefaultInstance();
      }

      @java.lang.Override
      public de.starwit.visionapi.Analytics.DetectionCountMessage build() {
        de.starwit.visionapi.Analytics.DetectionCountMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public de.starwit.visionapi.Analytics.DetectionCountMessage buildPartial() {
        de.starwit.visionapi.Analytics.DetectionCountMessage result = new de.starwit.visionapi.Analytics.DetectionCountMessage(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(de.starwit.visionapi.Analytics.DetectionCountMessage result) {
        if (detectionCountsBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0)) {
            detectionCounts_ = java.util.Collections.unmodifiableList(detectionCounts_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.detectionCounts_ = detectionCounts_;
        } else {
          result.detectionCounts_ = detectionCountsBuilder_.build();
        }
      }

      private void buildPartial0(de.starwit.visionapi.Analytics.DetectionCountMessage result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.timestampUtcMs_ = timestampUtcMs_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.saeUuid_ = saeUuid_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.type_ = type_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof de.starwit.visionapi.Analytics.DetectionCountMessage) {
          return mergeFrom((de.starwit.visionapi.Analytics.DetectionCountMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(de.starwit.visionapi.Analytics.DetectionCountMessage other) {
        if (other == de.starwit.visionapi.Analytics.DetectionCountMessage.getDefaultInstance()) return this;
        if (other.getTimestampUtcMs() != 0L) {
          setTimestampUtcMs(other.getTimestampUtcMs());
        }
        if (detectionCountsBuilder_ == null) {
          if (!other.detectionCounts_.isEmpty()) {
            if (detectionCounts_.isEmpty()) {
              detectionCounts_ = other.detectionCounts_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureDetectionCountsIsMutable();
              detectionCounts_.addAll(other.detectionCounts_);
            }
            onChanged();
          }
        } else {
          if (!other.detectionCounts_.isEmpty()) {
            if (detectionCountsBuilder_.isEmpty()) {
              detectionCountsBuilder_.dispose();
              detectionCountsBuilder_ = null;
              detectionCounts_ = other.detectionCounts_;
              bitField0_ = (bitField0_ & ~0x00000002);
              detectionCountsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   internalGetDetectionCountsFieldBuilder() : null;
            } else {
              detectionCountsBuilder_.addAllMessages(other.detectionCounts_);
            }
          }
        }
        if (!other.getSaeUuid().isEmpty()) {
          setSaeUuid(other.getSaeUuid());
        }
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                timestampUtcMs_ = input.readUInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                de.starwit.visionapi.Analytics.DetectionCount m =
                    input.readMessage(
                        de.starwit.visionapi.Analytics.DetectionCount.parser(),
                        extensionRegistry);
                if (detectionCountsBuilder_ == null) {
                  ensureDetectionCountsIsMutable();
                  detectionCounts_.add(m);
                } else {
                  detectionCountsBuilder_.addMessage(m);
                }
                break;
              } // case 18
              case 34: {
                saeUuid_ = input.readBytes();
                bitField0_ |= 0x00000004;
                break;
              } // case 34
              case 8000: {
                type_ = input.readEnum();
                bitField0_ |= 0x00000008;
                break;
              } // case 8000
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long timestampUtcMs_ ;
      /**
       * <pre>
       * Zeitpunkt der Message-Erstellung, Zeitintervall wird in der Komponenten eingestellt
       * </pre>
       *
       * <code>uint64 timestamp_utc_ms = 1;</code>
       * @return The timestampUtcMs.
       */
      @java.lang.Override
      public long getTimestampUtcMs() {
        return timestampUtcMs_;
      }
      /**
       * <pre>
       * Zeitpunkt der Message-Erstellung, Zeitintervall wird in der Komponenten eingestellt
       * </pre>
       *
       * <code>uint64 timestamp_utc_ms = 1;</code>
       * @param value The timestampUtcMs to set.
       * @return This builder for chaining.
       */
      public Builder setTimestampUtcMs(long value) {

        timestampUtcMs_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Zeitpunkt der Message-Erstellung, Zeitintervall wird in der Komponenten eingestellt
       * </pre>
       *
       * <code>uint64 timestamp_utc_ms = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimestampUtcMs() {
        bitField0_ = (bitField0_ & ~0x00000001);
        timestampUtcMs_ = 0L;
        onChanged();
        return this;
      }

      private java.util.List<de.starwit.visionapi.Analytics.DetectionCount> detectionCounts_ =
        java.util.Collections.emptyList();
      private void ensureDetectionCountsIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          detectionCounts_ = new java.util.ArrayList<de.starwit.visionapi.Analytics.DetectionCount>(detectionCounts_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          de.starwit.visionapi.Analytics.DetectionCount, de.starwit.visionapi.Analytics.DetectionCount.Builder, de.starwit.visionapi.Analytics.DetectionCountOrBuilder> detectionCountsBuilder_;

      /**
       * <code>repeated .visionapi.DetectionCount detection_counts = 2;</code>
       */
      public java.util.List<de.starwit.visionapi.Analytics.DetectionCount> getDetectionCountsList() {
        if (detectionCountsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(detectionCounts_);
        } else {
          return detectionCountsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .visionapi.DetectionCount detection_counts = 2;</code>
       */
      public int getDetectionCountsCount() {
        if (detectionCountsBuilder_ == null) {
          return detectionCounts_.size();
        } else {
          return detectionCountsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .visionapi.DetectionCount detection_counts = 2;</code>
       */
      public de.starwit.visionapi.Analytics.DetectionCount getDetectionCounts(int index) {
        if (detectionCountsBuilder_ == null) {
          return detectionCounts_.get(index);
        } else {
          return detectionCountsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .visionapi.DetectionCount detection_counts = 2;</code>
       */
      public Builder setDetectionCounts(
          int index, de.starwit.visionapi.Analytics.DetectionCount value) {
        if (detectionCountsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDetectionCountsIsMutable();
          detectionCounts_.set(index, value);
          onChanged();
        } else {
          detectionCountsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .visionapi.DetectionCount detection_counts = 2;</code>
       */
      public Builder setDetectionCounts(
          int index, de.starwit.visionapi.Analytics.DetectionCount.Builder builderForValue) {
        if (detectionCountsBuilder_ == null) {
          ensureDetectionCountsIsMutable();
          detectionCounts_.set(index, builderForValue.build());
          onChanged();
        } else {
          detectionCountsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .visionapi.DetectionCount detection_counts = 2;</code>
       */
      public Builder addDetectionCounts(de.starwit.visionapi.Analytics.DetectionCount value) {
        if (detectionCountsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDetectionCountsIsMutable();
          detectionCounts_.add(value);
          onChanged();
        } else {
          detectionCountsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .visionapi.DetectionCount detection_counts = 2;</code>
       */
      public Builder addDetectionCounts(
          int index, de.starwit.visionapi.Analytics.DetectionCount value) {
        if (detectionCountsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDetectionCountsIsMutable();
          detectionCounts_.add(index, value);
          onChanged();
        } else {
          detectionCountsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .visionapi.DetectionCount detection_counts = 2;</code>
       */
      public Builder addDetectionCounts(
          de.starwit.visionapi.Analytics.DetectionCount.Builder builderForValue) {
        if (detectionCountsBuilder_ == null) {
          ensureDetectionCountsIsMutable();
          detectionCounts_.add(builderForValue.build());
          onChanged();
        } else {
          detectionCountsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .visionapi.DetectionCount detection_counts = 2;</code>
       */
      public Builder addDetectionCounts(
          int index, de.starwit.visionapi.Analytics.DetectionCount.Builder builderForValue) {
        if (detectionCountsBuilder_ == null) {
          ensureDetectionCountsIsMutable();
          detectionCounts_.add(index, builderForValue.build());
          onChanged();
        } else {
          detectionCountsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .visionapi.DetectionCount detection_counts = 2;</code>
       */
      public Builder addAllDetectionCounts(
          java.lang.Iterable<? extends de.starwit.visionapi.Analytics.DetectionCount> values) {
        if (detectionCountsBuilder_ == null) {
          ensureDetectionCountsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, detectionCounts_);
          onChanged();
        } else {
          detectionCountsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .visionapi.DetectionCount detection_counts = 2;</code>
       */
      public Builder clearDetectionCounts() {
        if (detectionCountsBuilder_ == null) {
          detectionCounts_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          detectionCountsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .visionapi.DetectionCount detection_counts = 2;</code>
       */
      public Builder removeDetectionCounts(int index) {
        if (detectionCountsBuilder_ == null) {
          ensureDetectionCountsIsMutable();
          detectionCounts_.remove(index);
          onChanged();
        } else {
          detectionCountsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .visionapi.DetectionCount detection_counts = 2;</code>
       */
      public de.starwit.visionapi.Analytics.DetectionCount.Builder getDetectionCountsBuilder(
          int index) {
        return internalGetDetectionCountsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .visionapi.DetectionCount detection_counts = 2;</code>
       */
      public de.starwit.visionapi.Analytics.DetectionCountOrBuilder getDetectionCountsOrBuilder(
          int index) {
        if (detectionCountsBuilder_ == null) {
          return detectionCounts_.get(index);  } else {
          return detectionCountsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .visionapi.DetectionCount detection_counts = 2;</code>
       */
      public java.util.List<? extends de.starwit.visionapi.Analytics.DetectionCountOrBuilder> 
           getDetectionCountsOrBuilderList() {
        if (detectionCountsBuilder_ != null) {
          return detectionCountsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(detectionCounts_);
        }
      }
      /**
       * <code>repeated .visionapi.DetectionCount detection_counts = 2;</code>
       */
      public de.starwit.visionapi.Analytics.DetectionCount.Builder addDetectionCountsBuilder() {
        return internalGetDetectionCountsFieldBuilder().addBuilder(
            de.starwit.visionapi.Analytics.DetectionCount.getDefaultInstance());
      }
      /**
       * <code>repeated .visionapi.DetectionCount detection_counts = 2;</code>
       */
      public de.starwit.visionapi.Analytics.DetectionCount.Builder addDetectionCountsBuilder(
          int index) {
        return internalGetDetectionCountsFieldBuilder().addBuilder(
            index, de.starwit.visionapi.Analytics.DetectionCount.getDefaultInstance());
      }
      /**
       * <code>repeated .visionapi.DetectionCount detection_counts = 2;</code>
       */
      public java.util.List<de.starwit.visionapi.Analytics.DetectionCount.Builder> 
           getDetectionCountsBuilderList() {
        return internalGetDetectionCountsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          de.starwit.visionapi.Analytics.DetectionCount, de.starwit.visionapi.Analytics.DetectionCount.Builder, de.starwit.visionapi.Analytics.DetectionCountOrBuilder> 
          internalGetDetectionCountsFieldBuilder() {
        if (detectionCountsBuilder_ == null) {
          detectionCountsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              de.starwit.visionapi.Analytics.DetectionCount, de.starwit.visionapi.Analytics.DetectionCount.Builder, de.starwit.visionapi.Analytics.DetectionCountOrBuilder>(
                  detectionCounts_,
                  ((bitField0_ & 0x00000002) != 0),
                  getParentForChildren(),
                  isClean());
          detectionCounts_ = null;
        }
        return detectionCountsBuilder_;
      }

      private com.google.protobuf.ByteString saeUuid_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes sae_uuid = 4;</code>
       * @return The saeUuid.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getSaeUuid() {
        return saeUuid_;
      }
      /**
       * <code>bytes sae_uuid = 4;</code>
       * @param value The saeUuid to set.
       * @return This builder for chaining.
       */
      public Builder setSaeUuid(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        saeUuid_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>bytes sae_uuid = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearSaeUuid() {
        bitField0_ = (bitField0_ & ~0x00000004);
        saeUuid_ = getDefaultInstance().getSaeUuid();
        onChanged();
        return this;
      }

      private int type_ = 0;
      /**
       * <code>.visionapi.MessageType type = 1000;</code>
       * @return The enum numeric value on the wire for type.
       */
      @java.lang.Override public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.visionapi.MessageType type = 1000;</code>
       * @param value The enum numeric value on the wire for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>.visionapi.MessageType type = 1000;</code>
       * @return The type.
       */
      @java.lang.Override
      public de.starwit.visionapi.Common.MessageType getType() {
        de.starwit.visionapi.Common.MessageType result = de.starwit.visionapi.Common.MessageType.forNumber(type_);
        return result == null ? de.starwit.visionapi.Common.MessageType.UNRECOGNIZED : result;
      }
      /**
       * <code>.visionapi.MessageType type = 1000;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(de.starwit.visionapi.Common.MessageType value) {
        if (value == null) { throw new NullPointerException(); }
        bitField0_ |= 0x00000008;
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.visionapi.MessageType type = 1000;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000008);
        type_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:visionapi.DetectionCountMessage)
    }

    // @@protoc_insertion_point(class_scope:visionapi.DetectionCountMessage)
    private static final de.starwit.visionapi.Analytics.DetectionCountMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new de.starwit.visionapi.Analytics.DetectionCountMessage();
    }

    public static de.starwit.visionapi.Analytics.DetectionCountMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DetectionCountMessage>
        PARSER = new com.google.protobuf.AbstractParser<DetectionCountMessage>() {
      @java.lang.Override
      public DetectionCountMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<DetectionCountMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DetectionCountMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public de.starwit.visionapi.Analytics.DetectionCountMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface DetectionCountOrBuilder extends
      // @@protoc_insertion_point(interface_extends:visionapi.DetectionCount)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint32 class_id = 1;</code>
     * @return The classId.
     */
    int getClassId();

    /**
     * <code>uint32 class_name = 10;</code>
     * @return The className.
     */
    int getClassName();

    /**
     * <code>uint32 count = 2;</code>
     * @return The count.
     */
    int getCount();

    /**
     * <code>.visionapi.GeoCoordinate location = 3;</code>
     * @return Whether the location field is set.
     */
    boolean hasLocation();
    /**
     * <code>.visionapi.GeoCoordinate location = 3;</code>
     * @return The location.
     */
    de.starwit.visionapi.Common.GeoCoordinate getLocation();
    /**
     * <code>.visionapi.GeoCoordinate location = 3;</code>
     */
    de.starwit.visionapi.Common.GeoCoordinateOrBuilder getLocationOrBuilder();
  }
  /**
   * Protobuf type {@code visionapi.DetectionCount}
   */
  public static final class DetectionCount extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:visionapi.DetectionCount)
      DetectionCountOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 31,
        /* patch= */ 1,
        /* suffix= */ "",
        DetectionCount.class.getName());
    }
    // Use DetectionCount.newBuilder() to construct.
    private DetectionCount(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private DetectionCount() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return de.starwit.visionapi.Analytics.internal_static_visionapi_DetectionCount_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return de.starwit.visionapi.Analytics.internal_static_visionapi_DetectionCount_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              de.starwit.visionapi.Analytics.DetectionCount.class, de.starwit.visionapi.Analytics.DetectionCount.Builder.class);
    }

    private int bitField0_;
    public static final int CLASS_ID_FIELD_NUMBER = 1;
    private int classId_ = 0;
    /**
     * <code>uint32 class_id = 1;</code>
     * @return The classId.
     */
    @java.lang.Override
    public int getClassId() {
      return classId_;
    }

    public static final int CLASS_NAME_FIELD_NUMBER = 10;
    private int className_ = 0;
    /**
     * <code>uint32 class_name = 10;</code>
     * @return The className.
     */
    @java.lang.Override
    public int getClassName() {
      return className_;
    }

    public static final int COUNT_FIELD_NUMBER = 2;
    private int count_ = 0;
    /**
     * <code>uint32 count = 2;</code>
     * @return The count.
     */
    @java.lang.Override
    public int getCount() {
      return count_;
    }

    public static final int LOCATION_FIELD_NUMBER = 3;
    private de.starwit.visionapi.Common.GeoCoordinate location_;
    /**
     * <code>.visionapi.GeoCoordinate location = 3;</code>
     * @return Whether the location field is set.
     */
    @java.lang.Override
    public boolean hasLocation() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.visionapi.GeoCoordinate location = 3;</code>
     * @return The location.
     */
    @java.lang.Override
    public de.starwit.visionapi.Common.GeoCoordinate getLocation() {
      return location_ == null ? de.starwit.visionapi.Common.GeoCoordinate.getDefaultInstance() : location_;
    }
    /**
     * <code>.visionapi.GeoCoordinate location = 3;</code>
     */
    @java.lang.Override
    public de.starwit.visionapi.Common.GeoCoordinateOrBuilder getLocationOrBuilder() {
      return location_ == null ? de.starwit.visionapi.Common.GeoCoordinate.getDefaultInstance() : location_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (classId_ != 0) {
        output.writeUInt32(1, classId_);
      }
      if (count_ != 0) {
        output.writeUInt32(2, count_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(3, getLocation());
      }
      if (className_ != 0) {
        output.writeUInt32(10, className_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (classId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, classId_);
      }
      if (count_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, count_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getLocation());
      }
      if (className_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(10, className_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof de.starwit.visionapi.Analytics.DetectionCount)) {
        return super.equals(obj);
      }
      de.starwit.visionapi.Analytics.DetectionCount other = (de.starwit.visionapi.Analytics.DetectionCount) obj;

      if (getClassId()
          != other.getClassId()) return false;
      if (getClassName()
          != other.getClassName()) return false;
      if (getCount()
          != other.getCount()) return false;
      if (hasLocation() != other.hasLocation()) return false;
      if (hasLocation()) {
        if (!getLocation()
            .equals(other.getLocation())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CLASS_ID_FIELD_NUMBER;
      hash = (53 * hash) + getClassId();
      hash = (37 * hash) + CLASS_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getClassName();
      hash = (37 * hash) + COUNT_FIELD_NUMBER;
      hash = (53 * hash) + getCount();
      if (hasLocation()) {
        hash = (37 * hash) + LOCATION_FIELD_NUMBER;
        hash = (53 * hash) + getLocation().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static de.starwit.visionapi.Analytics.DetectionCount parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.starwit.visionapi.Analytics.DetectionCount parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.starwit.visionapi.Analytics.DetectionCount parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.starwit.visionapi.Analytics.DetectionCount parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.starwit.visionapi.Analytics.DetectionCount parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.starwit.visionapi.Analytics.DetectionCount parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.starwit.visionapi.Analytics.DetectionCount parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static de.starwit.visionapi.Analytics.DetectionCount parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static de.starwit.visionapi.Analytics.DetectionCount parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static de.starwit.visionapi.Analytics.DetectionCount parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static de.starwit.visionapi.Analytics.DetectionCount parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static de.starwit.visionapi.Analytics.DetectionCount parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(de.starwit.visionapi.Analytics.DetectionCount prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code visionapi.DetectionCount}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:visionapi.DetectionCount)
        de.starwit.visionapi.Analytics.DetectionCountOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return de.starwit.visionapi.Analytics.internal_static_visionapi_DetectionCount_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return de.starwit.visionapi.Analytics.internal_static_visionapi_DetectionCount_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                de.starwit.visionapi.Analytics.DetectionCount.class, de.starwit.visionapi.Analytics.DetectionCount.Builder.class);
      }

      // Construct using de.starwit.visionapi.Analytics.DetectionCount.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage
                .alwaysUseFieldBuilders) {
          internalGetLocationFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        classId_ = 0;
        className_ = 0;
        count_ = 0;
        location_ = null;
        if (locationBuilder_ != null) {
          locationBuilder_.dispose();
          locationBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return de.starwit.visionapi.Analytics.internal_static_visionapi_DetectionCount_descriptor;
      }

      @java.lang.Override
      public de.starwit.visionapi.Analytics.DetectionCount getDefaultInstanceForType() {
        return de.starwit.visionapi.Analytics.DetectionCount.getDefaultInstance();
      }

      @java.lang.Override
      public de.starwit.visionapi.Analytics.DetectionCount build() {
        de.starwit.visionapi.Analytics.DetectionCount result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public de.starwit.visionapi.Analytics.DetectionCount buildPartial() {
        de.starwit.visionapi.Analytics.DetectionCount result = new de.starwit.visionapi.Analytics.DetectionCount(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(de.starwit.visionapi.Analytics.DetectionCount result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.classId_ = classId_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.className_ = className_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.count_ = count_;
        }
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.location_ = locationBuilder_ == null
              ? location_
              : locationBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof de.starwit.visionapi.Analytics.DetectionCount) {
          return mergeFrom((de.starwit.visionapi.Analytics.DetectionCount)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(de.starwit.visionapi.Analytics.DetectionCount other) {
        if (other == de.starwit.visionapi.Analytics.DetectionCount.getDefaultInstance()) return this;
        if (other.getClassId() != 0) {
          setClassId(other.getClassId());
        }
        if (other.getClassName() != 0) {
          setClassName(other.getClassName());
        }
        if (other.getCount() != 0) {
          setCount(other.getCount());
        }
        if (other.hasLocation()) {
          mergeLocation(other.getLocation());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                classId_ = input.readUInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                count_ = input.readUInt32();
                bitField0_ |= 0x00000004;
                break;
              } // case 16
              case 26: {
                input.readMessage(
                    internalGetLocationFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000008;
                break;
              } // case 26
              case 80: {
                className_ = input.readUInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 80
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int classId_ ;
      /**
       * <code>uint32 class_id = 1;</code>
       * @return The classId.
       */
      @java.lang.Override
      public int getClassId() {
        return classId_;
      }
      /**
       * <code>uint32 class_id = 1;</code>
       * @param value The classId to set.
       * @return This builder for chaining.
       */
      public Builder setClassId(int value) {

        classId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 class_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearClassId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        classId_ = 0;
        onChanged();
        return this;
      }

      private int className_ ;
      /**
       * <code>uint32 class_name = 10;</code>
       * @return The className.
       */
      @java.lang.Override
      public int getClassName() {
        return className_;
      }
      /**
       * <code>uint32 class_name = 10;</code>
       * @param value The className to set.
       * @return This builder for chaining.
       */
      public Builder setClassName(int value) {

        className_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 class_name = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearClassName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        className_ = 0;
        onChanged();
        return this;
      }

      private int count_ ;
      /**
       * <code>uint32 count = 2;</code>
       * @return The count.
       */
      @java.lang.Override
      public int getCount() {
        return count_;
      }
      /**
       * <code>uint32 count = 2;</code>
       * @param value The count to set.
       * @return This builder for chaining.
       */
      public Builder setCount(int value) {

        count_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 count = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearCount() {
        bitField0_ = (bitField0_ & ~0x00000004);
        count_ = 0;
        onChanged();
        return this;
      }

      private de.starwit.visionapi.Common.GeoCoordinate location_;
      private com.google.protobuf.SingleFieldBuilder<
          de.starwit.visionapi.Common.GeoCoordinate, de.starwit.visionapi.Common.GeoCoordinate.Builder, de.starwit.visionapi.Common.GeoCoordinateOrBuilder> locationBuilder_;
      /**
       * <code>.visionapi.GeoCoordinate location = 3;</code>
       * @return Whether the location field is set.
       */
      public boolean hasLocation() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>.visionapi.GeoCoordinate location = 3;</code>
       * @return The location.
       */
      public de.starwit.visionapi.Common.GeoCoordinate getLocation() {
        if (locationBuilder_ == null) {
          return location_ == null ? de.starwit.visionapi.Common.GeoCoordinate.getDefaultInstance() : location_;
        } else {
          return locationBuilder_.getMessage();
        }
      }
      /**
       * <code>.visionapi.GeoCoordinate location = 3;</code>
       */
      public Builder setLocation(de.starwit.visionapi.Common.GeoCoordinate value) {
        if (locationBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          location_ = value;
        } else {
          locationBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>.visionapi.GeoCoordinate location = 3;</code>
       */
      public Builder setLocation(
          de.starwit.visionapi.Common.GeoCoordinate.Builder builderForValue) {
        if (locationBuilder_ == null) {
          location_ = builderForValue.build();
        } else {
          locationBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>.visionapi.GeoCoordinate location = 3;</code>
       */
      public Builder mergeLocation(de.starwit.visionapi.Common.GeoCoordinate value) {
        if (locationBuilder_ == null) {
          if (((bitField0_ & 0x00000008) != 0) &&
            location_ != null &&
            location_ != de.starwit.visionapi.Common.GeoCoordinate.getDefaultInstance()) {
            getLocationBuilder().mergeFrom(value);
          } else {
            location_ = value;
          }
        } else {
          locationBuilder_.mergeFrom(value);
        }
        if (location_ != null) {
          bitField0_ |= 0x00000008;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.visionapi.GeoCoordinate location = 3;</code>
       */
      public Builder clearLocation() {
        bitField0_ = (bitField0_ & ~0x00000008);
        location_ = null;
        if (locationBuilder_ != null) {
          locationBuilder_.dispose();
          locationBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.visionapi.GeoCoordinate location = 3;</code>
       */
      public de.starwit.visionapi.Common.GeoCoordinate.Builder getLocationBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return internalGetLocationFieldBuilder().getBuilder();
      }
      /**
       * <code>.visionapi.GeoCoordinate location = 3;</code>
       */
      public de.starwit.visionapi.Common.GeoCoordinateOrBuilder getLocationOrBuilder() {
        if (locationBuilder_ != null) {
          return locationBuilder_.getMessageOrBuilder();
        } else {
          return location_ == null ?
              de.starwit.visionapi.Common.GeoCoordinate.getDefaultInstance() : location_;
        }
      }
      /**
       * <code>.visionapi.GeoCoordinate location = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          de.starwit.visionapi.Common.GeoCoordinate, de.starwit.visionapi.Common.GeoCoordinate.Builder, de.starwit.visionapi.Common.GeoCoordinateOrBuilder> 
          internalGetLocationFieldBuilder() {
        if (locationBuilder_ == null) {
          locationBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              de.starwit.visionapi.Common.GeoCoordinate, de.starwit.visionapi.Common.GeoCoordinate.Builder, de.starwit.visionapi.Common.GeoCoordinateOrBuilder>(
                  getLocation(),
                  getParentForChildren(),
                  isClean());
          location_ = null;
        }
        return locationBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:visionapi.DetectionCount)
    }

    // @@protoc_insertion_point(class_scope:visionapi.DetectionCount)
    private static final de.starwit.visionapi.Analytics.DetectionCount DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new de.starwit.visionapi.Analytics.DetectionCount();
    }

    public static de.starwit.visionapi.Analytics.DetectionCount getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DetectionCount>
        PARSER = new com.google.protobuf.AbstractParser<DetectionCount>() {
      @java.lang.Override
      public DetectionCount parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<DetectionCount> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DetectionCount> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public de.starwit.visionapi.Analytics.DetectionCount getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_visionapi_DetectionCountMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_visionapi_DetectionCountMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_visionapi_DetectionCount_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_visionapi_DetectionCount_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031visionapi/analytics.proto\022\tvisionapi\032\026" +
      "visionapi/common.proto\"\237\001\n\025DetectionCoun" +
      "tMessage\022\030\n\020timestamp_utc_ms\030\001 \001(\004\0223\n\020de" +
      "tection_counts\030\002 \003(\0132\031.visionapi.Detecti" +
      "onCount\022\020\n\010sae_uuid\030\004 \001(\014\022%\n\004type\030\350\007 \001(\016" +
      "2\026.visionapi.MessageType\"q\n\016DetectionCou" +
      "nt\022\020\n\010class_id\030\001 \001(\r\022\022\n\nclass_name\030\n \001(\r" +
      "\022\r\n\005count\030\002 \001(\r\022*\n\010location\030\003 \001(\0132\030.visi" +
      "onapi.GeoCoordinateB\026\n\024de.starwit.vision" +
      "apib\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          de.starwit.visionapi.Common.getDescriptor(),
        });
    internal_static_visionapi_DetectionCountMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_visionapi_DetectionCountMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_visionapi_DetectionCountMessage_descriptor,
        new java.lang.String[] { "TimestampUtcMs", "DetectionCounts", "SaeUuid", "Type", });
    internal_static_visionapi_DetectionCount_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_visionapi_DetectionCount_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_visionapi_DetectionCount_descriptor,
        new java.lang.String[] { "ClassId", "ClassName", "Count", "Location", });
    descriptor.resolveAllFeaturesImmutable();
    de.starwit.visionapi.Common.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
