// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: visionapi/tracker.proto

package de.starwit.visionapi;

public final class Tracker {
  private Tracker() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TrackingOutputOrBuilder extends
      // @@protoc_insertion_point(interface_extends:visionapi.TrackingOutput)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.visionapi.VideoFrame frame = 1;</code>
     * @return Whether the frame field is set.
     */
    boolean hasFrame();
    /**
     * <code>.visionapi.VideoFrame frame = 1;</code>
     * @return The frame.
     */
    de.starwit.visionapi.Videosource.VideoFrame getFrame();
    /**
     * <code>.visionapi.VideoFrame frame = 1;</code>
     */
    de.starwit.visionapi.Videosource.VideoFrameOrBuilder getFrameOrBuilder();

    /**
     * <code>repeated .visionapi.TrackedDetection tracked_detections = 2;</code>
     */
    java.util.List<de.starwit.visionapi.Tracker.TrackedDetection> 
        getTrackedDetectionsList();
    /**
     * <code>repeated .visionapi.TrackedDetection tracked_detections = 2;</code>
     */
    de.starwit.visionapi.Tracker.TrackedDetection getTrackedDetections(int index);
    /**
     * <code>repeated .visionapi.TrackedDetection tracked_detections = 2;</code>
     */
    int getTrackedDetectionsCount();
    /**
     * <code>repeated .visionapi.TrackedDetection tracked_detections = 2;</code>
     */
    java.util.List<? extends de.starwit.visionapi.Tracker.TrackedDetectionOrBuilder> 
        getTrackedDetectionsOrBuilderList();
    /**
     * <code>repeated .visionapi.TrackedDetection tracked_detections = 2;</code>
     */
    de.starwit.visionapi.Tracker.TrackedDetectionOrBuilder getTrackedDetectionsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code visionapi.TrackingOutput}
   */
  public static final class TrackingOutput extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:visionapi.TrackingOutput)
      TrackingOutputOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TrackingOutput.newBuilder() to construct.
    private TrackingOutput(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TrackingOutput() {
      trackedDetections_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new TrackingOutput();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return de.starwit.visionapi.Tracker.internal_static_visionapi_TrackingOutput_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return de.starwit.visionapi.Tracker.internal_static_visionapi_TrackingOutput_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              de.starwit.visionapi.Tracker.TrackingOutput.class, de.starwit.visionapi.Tracker.TrackingOutput.Builder.class);
    }

    public static final int FRAME_FIELD_NUMBER = 1;
    private de.starwit.visionapi.Videosource.VideoFrame frame_;
    /**
     * <code>.visionapi.VideoFrame frame = 1;</code>
     * @return Whether the frame field is set.
     */
    @java.lang.Override
    public boolean hasFrame() {
      return frame_ != null;
    }
    /**
     * <code>.visionapi.VideoFrame frame = 1;</code>
     * @return The frame.
     */
    @java.lang.Override
    public de.starwit.visionapi.Videosource.VideoFrame getFrame() {
      return frame_ == null ? de.starwit.visionapi.Videosource.VideoFrame.getDefaultInstance() : frame_;
    }
    /**
     * <code>.visionapi.VideoFrame frame = 1;</code>
     */
    @java.lang.Override
    public de.starwit.visionapi.Videosource.VideoFrameOrBuilder getFrameOrBuilder() {
      return frame_ == null ? de.starwit.visionapi.Videosource.VideoFrame.getDefaultInstance() : frame_;
    }

    public static final int TRACKED_DETECTIONS_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private java.util.List<de.starwit.visionapi.Tracker.TrackedDetection> trackedDetections_;
    /**
     * <code>repeated .visionapi.TrackedDetection tracked_detections = 2;</code>
     */
    @java.lang.Override
    public java.util.List<de.starwit.visionapi.Tracker.TrackedDetection> getTrackedDetectionsList() {
      return trackedDetections_;
    }
    /**
     * <code>repeated .visionapi.TrackedDetection tracked_detections = 2;</code>
     */
    @java.lang.Override
    public java.util.List<? extends de.starwit.visionapi.Tracker.TrackedDetectionOrBuilder> 
        getTrackedDetectionsOrBuilderList() {
      return trackedDetections_;
    }
    /**
     * <code>repeated .visionapi.TrackedDetection tracked_detections = 2;</code>
     */
    @java.lang.Override
    public int getTrackedDetectionsCount() {
      return trackedDetections_.size();
    }
    /**
     * <code>repeated .visionapi.TrackedDetection tracked_detections = 2;</code>
     */
    @java.lang.Override
    public de.starwit.visionapi.Tracker.TrackedDetection getTrackedDetections(int index) {
      return trackedDetections_.get(index);
    }
    /**
     * <code>repeated .visionapi.TrackedDetection tracked_detections = 2;</code>
     */
    @java.lang.Override
    public de.starwit.visionapi.Tracker.TrackedDetectionOrBuilder getTrackedDetectionsOrBuilder(
        int index) {
      return trackedDetections_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (frame_ != null) {
        output.writeMessage(1, getFrame());
      }
      for (int i = 0; i < trackedDetections_.size(); i++) {
        output.writeMessage(2, trackedDetections_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (frame_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getFrame());
      }
      for (int i = 0; i < trackedDetections_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, trackedDetections_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof de.starwit.visionapi.Tracker.TrackingOutput)) {
        return super.equals(obj);
      }
      de.starwit.visionapi.Tracker.TrackingOutput other = (de.starwit.visionapi.Tracker.TrackingOutput) obj;

      if (hasFrame() != other.hasFrame()) return false;
      if (hasFrame()) {
        if (!getFrame()
            .equals(other.getFrame())) return false;
      }
      if (!getTrackedDetectionsList()
          .equals(other.getTrackedDetectionsList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasFrame()) {
        hash = (37 * hash) + FRAME_FIELD_NUMBER;
        hash = (53 * hash) + getFrame().hashCode();
      }
      if (getTrackedDetectionsCount() > 0) {
        hash = (37 * hash) + TRACKED_DETECTIONS_FIELD_NUMBER;
        hash = (53 * hash) + getTrackedDetectionsList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static de.starwit.visionapi.Tracker.TrackingOutput parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.starwit.visionapi.Tracker.TrackingOutput parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.starwit.visionapi.Tracker.TrackingOutput parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.starwit.visionapi.Tracker.TrackingOutput parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.starwit.visionapi.Tracker.TrackingOutput parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.starwit.visionapi.Tracker.TrackingOutput parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.starwit.visionapi.Tracker.TrackingOutput parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static de.starwit.visionapi.Tracker.TrackingOutput parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static de.starwit.visionapi.Tracker.TrackingOutput parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static de.starwit.visionapi.Tracker.TrackingOutput parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static de.starwit.visionapi.Tracker.TrackingOutput parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static de.starwit.visionapi.Tracker.TrackingOutput parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(de.starwit.visionapi.Tracker.TrackingOutput prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code visionapi.TrackingOutput}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:visionapi.TrackingOutput)
        de.starwit.visionapi.Tracker.TrackingOutputOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return de.starwit.visionapi.Tracker.internal_static_visionapi_TrackingOutput_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return de.starwit.visionapi.Tracker.internal_static_visionapi_TrackingOutput_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                de.starwit.visionapi.Tracker.TrackingOutput.class, de.starwit.visionapi.Tracker.TrackingOutput.Builder.class);
      }

      // Construct using de.starwit.visionapi.Tracker.TrackingOutput.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        frame_ = null;
        if (frameBuilder_ != null) {
          frameBuilder_.dispose();
          frameBuilder_ = null;
        }
        if (trackedDetectionsBuilder_ == null) {
          trackedDetections_ = java.util.Collections.emptyList();
        } else {
          trackedDetections_ = null;
          trackedDetectionsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return de.starwit.visionapi.Tracker.internal_static_visionapi_TrackingOutput_descriptor;
      }

      @java.lang.Override
      public de.starwit.visionapi.Tracker.TrackingOutput getDefaultInstanceForType() {
        return de.starwit.visionapi.Tracker.TrackingOutput.getDefaultInstance();
      }

      @java.lang.Override
      public de.starwit.visionapi.Tracker.TrackingOutput build() {
        de.starwit.visionapi.Tracker.TrackingOutput result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public de.starwit.visionapi.Tracker.TrackingOutput buildPartial() {
        de.starwit.visionapi.Tracker.TrackingOutput result = new de.starwit.visionapi.Tracker.TrackingOutput(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(de.starwit.visionapi.Tracker.TrackingOutput result) {
        if (trackedDetectionsBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0)) {
            trackedDetections_ = java.util.Collections.unmodifiableList(trackedDetections_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.trackedDetections_ = trackedDetections_;
        } else {
          result.trackedDetections_ = trackedDetectionsBuilder_.build();
        }
      }

      private void buildPartial0(de.starwit.visionapi.Tracker.TrackingOutput result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.frame_ = frameBuilder_ == null
              ? frame_
              : frameBuilder_.build();
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof de.starwit.visionapi.Tracker.TrackingOutput) {
          return mergeFrom((de.starwit.visionapi.Tracker.TrackingOutput)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(de.starwit.visionapi.Tracker.TrackingOutput other) {
        if (other == de.starwit.visionapi.Tracker.TrackingOutput.getDefaultInstance()) return this;
        if (other.hasFrame()) {
          mergeFrame(other.getFrame());
        }
        if (trackedDetectionsBuilder_ == null) {
          if (!other.trackedDetections_.isEmpty()) {
            if (trackedDetections_.isEmpty()) {
              trackedDetections_ = other.trackedDetections_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureTrackedDetectionsIsMutable();
              trackedDetections_.addAll(other.trackedDetections_);
            }
            onChanged();
          }
        } else {
          if (!other.trackedDetections_.isEmpty()) {
            if (trackedDetectionsBuilder_.isEmpty()) {
              trackedDetectionsBuilder_.dispose();
              trackedDetectionsBuilder_ = null;
              trackedDetections_ = other.trackedDetections_;
              bitField0_ = (bitField0_ & ~0x00000002);
              trackedDetectionsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getTrackedDetectionsFieldBuilder() : null;
            } else {
              trackedDetectionsBuilder_.addAllMessages(other.trackedDetections_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    getFrameFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                de.starwit.visionapi.Tracker.TrackedDetection m =
                    input.readMessage(
                        de.starwit.visionapi.Tracker.TrackedDetection.parser(),
                        extensionRegistry);
                if (trackedDetectionsBuilder_ == null) {
                  ensureTrackedDetectionsIsMutable();
                  trackedDetections_.add(m);
                } else {
                  trackedDetectionsBuilder_.addMessage(m);
                }
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private de.starwit.visionapi.Videosource.VideoFrame frame_;
      private com.google.protobuf.SingleFieldBuilderV3<
          de.starwit.visionapi.Videosource.VideoFrame, de.starwit.visionapi.Videosource.VideoFrame.Builder, de.starwit.visionapi.Videosource.VideoFrameOrBuilder> frameBuilder_;
      /**
       * <code>.visionapi.VideoFrame frame = 1;</code>
       * @return Whether the frame field is set.
       */
      public boolean hasFrame() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>.visionapi.VideoFrame frame = 1;</code>
       * @return The frame.
       */
      public de.starwit.visionapi.Videosource.VideoFrame getFrame() {
        if (frameBuilder_ == null) {
          return frame_ == null ? de.starwit.visionapi.Videosource.VideoFrame.getDefaultInstance() : frame_;
        } else {
          return frameBuilder_.getMessage();
        }
      }
      /**
       * <code>.visionapi.VideoFrame frame = 1;</code>
       */
      public Builder setFrame(de.starwit.visionapi.Videosource.VideoFrame value) {
        if (frameBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          frame_ = value;
        } else {
          frameBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.visionapi.VideoFrame frame = 1;</code>
       */
      public Builder setFrame(
          de.starwit.visionapi.Videosource.VideoFrame.Builder builderForValue) {
        if (frameBuilder_ == null) {
          frame_ = builderForValue.build();
        } else {
          frameBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.visionapi.VideoFrame frame = 1;</code>
       */
      public Builder mergeFrame(de.starwit.visionapi.Videosource.VideoFrame value) {
        if (frameBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
            frame_ != null &&
            frame_ != de.starwit.visionapi.Videosource.VideoFrame.getDefaultInstance()) {
            getFrameBuilder().mergeFrom(value);
          } else {
            frame_ = value;
          }
        } else {
          frameBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.visionapi.VideoFrame frame = 1;</code>
       */
      public Builder clearFrame() {
        bitField0_ = (bitField0_ & ~0x00000001);
        frame_ = null;
        if (frameBuilder_ != null) {
          frameBuilder_.dispose();
          frameBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.visionapi.VideoFrame frame = 1;</code>
       */
      public de.starwit.visionapi.Videosource.VideoFrame.Builder getFrameBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getFrameFieldBuilder().getBuilder();
      }
      /**
       * <code>.visionapi.VideoFrame frame = 1;</code>
       */
      public de.starwit.visionapi.Videosource.VideoFrameOrBuilder getFrameOrBuilder() {
        if (frameBuilder_ != null) {
          return frameBuilder_.getMessageOrBuilder();
        } else {
          return frame_ == null ?
              de.starwit.visionapi.Videosource.VideoFrame.getDefaultInstance() : frame_;
        }
      }
      /**
       * <code>.visionapi.VideoFrame frame = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          de.starwit.visionapi.Videosource.VideoFrame, de.starwit.visionapi.Videosource.VideoFrame.Builder, de.starwit.visionapi.Videosource.VideoFrameOrBuilder> 
          getFrameFieldBuilder() {
        if (frameBuilder_ == null) {
          frameBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              de.starwit.visionapi.Videosource.VideoFrame, de.starwit.visionapi.Videosource.VideoFrame.Builder, de.starwit.visionapi.Videosource.VideoFrameOrBuilder>(
                  getFrame(),
                  getParentForChildren(),
                  isClean());
          frame_ = null;
        }
        return frameBuilder_;
      }

      private java.util.List<de.starwit.visionapi.Tracker.TrackedDetection> trackedDetections_ =
        java.util.Collections.emptyList();
      private void ensureTrackedDetectionsIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          trackedDetections_ = new java.util.ArrayList<de.starwit.visionapi.Tracker.TrackedDetection>(trackedDetections_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          de.starwit.visionapi.Tracker.TrackedDetection, de.starwit.visionapi.Tracker.TrackedDetection.Builder, de.starwit.visionapi.Tracker.TrackedDetectionOrBuilder> trackedDetectionsBuilder_;

      /**
       * <code>repeated .visionapi.TrackedDetection tracked_detections = 2;</code>
       */
      public java.util.List<de.starwit.visionapi.Tracker.TrackedDetection> getTrackedDetectionsList() {
        if (trackedDetectionsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(trackedDetections_);
        } else {
          return trackedDetectionsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .visionapi.TrackedDetection tracked_detections = 2;</code>
       */
      public int getTrackedDetectionsCount() {
        if (trackedDetectionsBuilder_ == null) {
          return trackedDetections_.size();
        } else {
          return trackedDetectionsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .visionapi.TrackedDetection tracked_detections = 2;</code>
       */
      public de.starwit.visionapi.Tracker.TrackedDetection getTrackedDetections(int index) {
        if (trackedDetectionsBuilder_ == null) {
          return trackedDetections_.get(index);
        } else {
          return trackedDetectionsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .visionapi.TrackedDetection tracked_detections = 2;</code>
       */
      public Builder setTrackedDetections(
          int index, de.starwit.visionapi.Tracker.TrackedDetection value) {
        if (trackedDetectionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTrackedDetectionsIsMutable();
          trackedDetections_.set(index, value);
          onChanged();
        } else {
          trackedDetectionsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .visionapi.TrackedDetection tracked_detections = 2;</code>
       */
      public Builder setTrackedDetections(
          int index, de.starwit.visionapi.Tracker.TrackedDetection.Builder builderForValue) {
        if (trackedDetectionsBuilder_ == null) {
          ensureTrackedDetectionsIsMutable();
          trackedDetections_.set(index, builderForValue.build());
          onChanged();
        } else {
          trackedDetectionsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .visionapi.TrackedDetection tracked_detections = 2;</code>
       */
      public Builder addTrackedDetections(de.starwit.visionapi.Tracker.TrackedDetection value) {
        if (trackedDetectionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTrackedDetectionsIsMutable();
          trackedDetections_.add(value);
          onChanged();
        } else {
          trackedDetectionsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .visionapi.TrackedDetection tracked_detections = 2;</code>
       */
      public Builder addTrackedDetections(
          int index, de.starwit.visionapi.Tracker.TrackedDetection value) {
        if (trackedDetectionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTrackedDetectionsIsMutable();
          trackedDetections_.add(index, value);
          onChanged();
        } else {
          trackedDetectionsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .visionapi.TrackedDetection tracked_detections = 2;</code>
       */
      public Builder addTrackedDetections(
          de.starwit.visionapi.Tracker.TrackedDetection.Builder builderForValue) {
        if (trackedDetectionsBuilder_ == null) {
          ensureTrackedDetectionsIsMutable();
          trackedDetections_.add(builderForValue.build());
          onChanged();
        } else {
          trackedDetectionsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .visionapi.TrackedDetection tracked_detections = 2;</code>
       */
      public Builder addTrackedDetections(
          int index, de.starwit.visionapi.Tracker.TrackedDetection.Builder builderForValue) {
        if (trackedDetectionsBuilder_ == null) {
          ensureTrackedDetectionsIsMutable();
          trackedDetections_.add(index, builderForValue.build());
          onChanged();
        } else {
          trackedDetectionsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .visionapi.TrackedDetection tracked_detections = 2;</code>
       */
      public Builder addAllTrackedDetections(
          java.lang.Iterable<? extends de.starwit.visionapi.Tracker.TrackedDetection> values) {
        if (trackedDetectionsBuilder_ == null) {
          ensureTrackedDetectionsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, trackedDetections_);
          onChanged();
        } else {
          trackedDetectionsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .visionapi.TrackedDetection tracked_detections = 2;</code>
       */
      public Builder clearTrackedDetections() {
        if (trackedDetectionsBuilder_ == null) {
          trackedDetections_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          trackedDetectionsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .visionapi.TrackedDetection tracked_detections = 2;</code>
       */
      public Builder removeTrackedDetections(int index) {
        if (trackedDetectionsBuilder_ == null) {
          ensureTrackedDetectionsIsMutable();
          trackedDetections_.remove(index);
          onChanged();
        } else {
          trackedDetectionsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .visionapi.TrackedDetection tracked_detections = 2;</code>
       */
      public de.starwit.visionapi.Tracker.TrackedDetection.Builder getTrackedDetectionsBuilder(
          int index) {
        return getTrackedDetectionsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .visionapi.TrackedDetection tracked_detections = 2;</code>
       */
      public de.starwit.visionapi.Tracker.TrackedDetectionOrBuilder getTrackedDetectionsOrBuilder(
          int index) {
        if (trackedDetectionsBuilder_ == null) {
          return trackedDetections_.get(index);  } else {
          return trackedDetectionsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .visionapi.TrackedDetection tracked_detections = 2;</code>
       */
      public java.util.List<? extends de.starwit.visionapi.Tracker.TrackedDetectionOrBuilder> 
           getTrackedDetectionsOrBuilderList() {
        if (trackedDetectionsBuilder_ != null) {
          return trackedDetectionsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(trackedDetections_);
        }
      }
      /**
       * <code>repeated .visionapi.TrackedDetection tracked_detections = 2;</code>
       */
      public de.starwit.visionapi.Tracker.TrackedDetection.Builder addTrackedDetectionsBuilder() {
        return getTrackedDetectionsFieldBuilder().addBuilder(
            de.starwit.visionapi.Tracker.TrackedDetection.getDefaultInstance());
      }
      /**
       * <code>repeated .visionapi.TrackedDetection tracked_detections = 2;</code>
       */
      public de.starwit.visionapi.Tracker.TrackedDetection.Builder addTrackedDetectionsBuilder(
          int index) {
        return getTrackedDetectionsFieldBuilder().addBuilder(
            index, de.starwit.visionapi.Tracker.TrackedDetection.getDefaultInstance());
      }
      /**
       * <code>repeated .visionapi.TrackedDetection tracked_detections = 2;</code>
       */
      public java.util.List<de.starwit.visionapi.Tracker.TrackedDetection.Builder> 
           getTrackedDetectionsBuilderList() {
        return getTrackedDetectionsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          de.starwit.visionapi.Tracker.TrackedDetection, de.starwit.visionapi.Tracker.TrackedDetection.Builder, de.starwit.visionapi.Tracker.TrackedDetectionOrBuilder> 
          getTrackedDetectionsFieldBuilder() {
        if (trackedDetectionsBuilder_ == null) {
          trackedDetectionsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              de.starwit.visionapi.Tracker.TrackedDetection, de.starwit.visionapi.Tracker.TrackedDetection.Builder, de.starwit.visionapi.Tracker.TrackedDetectionOrBuilder>(
                  trackedDetections_,
                  ((bitField0_ & 0x00000002) != 0),
                  getParentForChildren(),
                  isClean());
          trackedDetections_ = null;
        }
        return trackedDetectionsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:visionapi.TrackingOutput)
    }

    // @@protoc_insertion_point(class_scope:visionapi.TrackingOutput)
    private static final de.starwit.visionapi.Tracker.TrackingOutput DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new de.starwit.visionapi.Tracker.TrackingOutput();
    }

    public static de.starwit.visionapi.Tracker.TrackingOutput getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TrackingOutput>
        PARSER = new com.google.protobuf.AbstractParser<TrackingOutput>() {
      @java.lang.Override
      public TrackingOutput parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<TrackingOutput> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TrackingOutput> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public de.starwit.visionapi.Tracker.TrackingOutput getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TrackedDetectionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:visionapi.TrackedDetection)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.visionapi.Detection detection = 1;</code>
     * @return Whether the detection field is set.
     */
    boolean hasDetection();
    /**
     * <code>.visionapi.Detection detection = 1;</code>
     * @return The detection.
     */
    de.starwit.visionapi.Detector.Detection getDetection();
    /**
     * <code>.visionapi.Detection detection = 1;</code>
     */
    de.starwit.visionapi.Detector.DetectionOrBuilder getDetectionOrBuilder();

    /**
     * <code>bytes object_id = 2;</code>
     * @return The objectId.
     */
    com.google.protobuf.ByteString getObjectId();
  }
  /**
   * Protobuf type {@code visionapi.TrackedDetection}
   */
  public static final class TrackedDetection extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:visionapi.TrackedDetection)
      TrackedDetectionOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TrackedDetection.newBuilder() to construct.
    private TrackedDetection(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TrackedDetection() {
      objectId_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new TrackedDetection();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return de.starwit.visionapi.Tracker.internal_static_visionapi_TrackedDetection_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return de.starwit.visionapi.Tracker.internal_static_visionapi_TrackedDetection_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              de.starwit.visionapi.Tracker.TrackedDetection.class, de.starwit.visionapi.Tracker.TrackedDetection.Builder.class);
    }

    public static final int DETECTION_FIELD_NUMBER = 1;
    private de.starwit.visionapi.Detector.Detection detection_;
    /**
     * <code>.visionapi.Detection detection = 1;</code>
     * @return Whether the detection field is set.
     */
    @java.lang.Override
    public boolean hasDetection() {
      return detection_ != null;
    }
    /**
     * <code>.visionapi.Detection detection = 1;</code>
     * @return The detection.
     */
    @java.lang.Override
    public de.starwit.visionapi.Detector.Detection getDetection() {
      return detection_ == null ? de.starwit.visionapi.Detector.Detection.getDefaultInstance() : detection_;
    }
    /**
     * <code>.visionapi.Detection detection = 1;</code>
     */
    @java.lang.Override
    public de.starwit.visionapi.Detector.DetectionOrBuilder getDetectionOrBuilder() {
      return detection_ == null ? de.starwit.visionapi.Detector.Detection.getDefaultInstance() : detection_;
    }

    public static final int OBJECT_ID_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString objectId_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes object_id = 2;</code>
     * @return The objectId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getObjectId() {
      return objectId_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (detection_ != null) {
        output.writeMessage(1, getDetection());
      }
      if (!objectId_.isEmpty()) {
        output.writeBytes(2, objectId_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (detection_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getDetection());
      }
      if (!objectId_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, objectId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof de.starwit.visionapi.Tracker.TrackedDetection)) {
        return super.equals(obj);
      }
      de.starwit.visionapi.Tracker.TrackedDetection other = (de.starwit.visionapi.Tracker.TrackedDetection) obj;

      if (hasDetection() != other.hasDetection()) return false;
      if (hasDetection()) {
        if (!getDetection()
            .equals(other.getDetection())) return false;
      }
      if (!getObjectId()
          .equals(other.getObjectId())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasDetection()) {
        hash = (37 * hash) + DETECTION_FIELD_NUMBER;
        hash = (53 * hash) + getDetection().hashCode();
      }
      hash = (37 * hash) + OBJECT_ID_FIELD_NUMBER;
      hash = (53 * hash) + getObjectId().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static de.starwit.visionapi.Tracker.TrackedDetection parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.starwit.visionapi.Tracker.TrackedDetection parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.starwit.visionapi.Tracker.TrackedDetection parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.starwit.visionapi.Tracker.TrackedDetection parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.starwit.visionapi.Tracker.TrackedDetection parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.starwit.visionapi.Tracker.TrackedDetection parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.starwit.visionapi.Tracker.TrackedDetection parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static de.starwit.visionapi.Tracker.TrackedDetection parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static de.starwit.visionapi.Tracker.TrackedDetection parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static de.starwit.visionapi.Tracker.TrackedDetection parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static de.starwit.visionapi.Tracker.TrackedDetection parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static de.starwit.visionapi.Tracker.TrackedDetection parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(de.starwit.visionapi.Tracker.TrackedDetection prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code visionapi.TrackedDetection}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:visionapi.TrackedDetection)
        de.starwit.visionapi.Tracker.TrackedDetectionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return de.starwit.visionapi.Tracker.internal_static_visionapi_TrackedDetection_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return de.starwit.visionapi.Tracker.internal_static_visionapi_TrackedDetection_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                de.starwit.visionapi.Tracker.TrackedDetection.class, de.starwit.visionapi.Tracker.TrackedDetection.Builder.class);
      }

      // Construct using de.starwit.visionapi.Tracker.TrackedDetection.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        detection_ = null;
        if (detectionBuilder_ != null) {
          detectionBuilder_.dispose();
          detectionBuilder_ = null;
        }
        objectId_ = com.google.protobuf.ByteString.EMPTY;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return de.starwit.visionapi.Tracker.internal_static_visionapi_TrackedDetection_descriptor;
      }

      @java.lang.Override
      public de.starwit.visionapi.Tracker.TrackedDetection getDefaultInstanceForType() {
        return de.starwit.visionapi.Tracker.TrackedDetection.getDefaultInstance();
      }

      @java.lang.Override
      public de.starwit.visionapi.Tracker.TrackedDetection build() {
        de.starwit.visionapi.Tracker.TrackedDetection result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public de.starwit.visionapi.Tracker.TrackedDetection buildPartial() {
        de.starwit.visionapi.Tracker.TrackedDetection result = new de.starwit.visionapi.Tracker.TrackedDetection(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(de.starwit.visionapi.Tracker.TrackedDetection result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.detection_ = detectionBuilder_ == null
              ? detection_
              : detectionBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.objectId_ = objectId_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof de.starwit.visionapi.Tracker.TrackedDetection) {
          return mergeFrom((de.starwit.visionapi.Tracker.TrackedDetection)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(de.starwit.visionapi.Tracker.TrackedDetection other) {
        if (other == de.starwit.visionapi.Tracker.TrackedDetection.getDefaultInstance()) return this;
        if (other.hasDetection()) {
          mergeDetection(other.getDetection());
        }
        if (other.getObjectId() != com.google.protobuf.ByteString.EMPTY) {
          setObjectId(other.getObjectId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    getDetectionFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                objectId_ = input.readBytes();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private de.starwit.visionapi.Detector.Detection detection_;
      private com.google.protobuf.SingleFieldBuilderV3<
          de.starwit.visionapi.Detector.Detection, de.starwit.visionapi.Detector.Detection.Builder, de.starwit.visionapi.Detector.DetectionOrBuilder> detectionBuilder_;
      /**
       * <code>.visionapi.Detection detection = 1;</code>
       * @return Whether the detection field is set.
       */
      public boolean hasDetection() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>.visionapi.Detection detection = 1;</code>
       * @return The detection.
       */
      public de.starwit.visionapi.Detector.Detection getDetection() {
        if (detectionBuilder_ == null) {
          return detection_ == null ? de.starwit.visionapi.Detector.Detection.getDefaultInstance() : detection_;
        } else {
          return detectionBuilder_.getMessage();
        }
      }
      /**
       * <code>.visionapi.Detection detection = 1;</code>
       */
      public Builder setDetection(de.starwit.visionapi.Detector.Detection value) {
        if (detectionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          detection_ = value;
        } else {
          detectionBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.visionapi.Detection detection = 1;</code>
       */
      public Builder setDetection(
          de.starwit.visionapi.Detector.Detection.Builder builderForValue) {
        if (detectionBuilder_ == null) {
          detection_ = builderForValue.build();
        } else {
          detectionBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.visionapi.Detection detection = 1;</code>
       */
      public Builder mergeDetection(de.starwit.visionapi.Detector.Detection value) {
        if (detectionBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
            detection_ != null &&
            detection_ != de.starwit.visionapi.Detector.Detection.getDefaultInstance()) {
            getDetectionBuilder().mergeFrom(value);
          } else {
            detection_ = value;
          }
        } else {
          detectionBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.visionapi.Detection detection = 1;</code>
       */
      public Builder clearDetection() {
        bitField0_ = (bitField0_ & ~0x00000001);
        detection_ = null;
        if (detectionBuilder_ != null) {
          detectionBuilder_.dispose();
          detectionBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.visionapi.Detection detection = 1;</code>
       */
      public de.starwit.visionapi.Detector.Detection.Builder getDetectionBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getDetectionFieldBuilder().getBuilder();
      }
      /**
       * <code>.visionapi.Detection detection = 1;</code>
       */
      public de.starwit.visionapi.Detector.DetectionOrBuilder getDetectionOrBuilder() {
        if (detectionBuilder_ != null) {
          return detectionBuilder_.getMessageOrBuilder();
        } else {
          return detection_ == null ?
              de.starwit.visionapi.Detector.Detection.getDefaultInstance() : detection_;
        }
      }
      /**
       * <code>.visionapi.Detection detection = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          de.starwit.visionapi.Detector.Detection, de.starwit.visionapi.Detector.Detection.Builder, de.starwit.visionapi.Detector.DetectionOrBuilder> 
          getDetectionFieldBuilder() {
        if (detectionBuilder_ == null) {
          detectionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              de.starwit.visionapi.Detector.Detection, de.starwit.visionapi.Detector.Detection.Builder, de.starwit.visionapi.Detector.DetectionOrBuilder>(
                  getDetection(),
                  getParentForChildren(),
                  isClean());
          detection_ = null;
        }
        return detectionBuilder_;
      }

      private com.google.protobuf.ByteString objectId_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes object_id = 2;</code>
       * @return The objectId.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getObjectId() {
        return objectId_;
      }
      /**
       * <code>bytes object_id = 2;</code>
       * @param value The objectId to set.
       * @return This builder for chaining.
       */
      public Builder setObjectId(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        objectId_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>bytes object_id = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearObjectId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        objectId_ = getDefaultInstance().getObjectId();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:visionapi.TrackedDetection)
    }

    // @@protoc_insertion_point(class_scope:visionapi.TrackedDetection)
    private static final de.starwit.visionapi.Tracker.TrackedDetection DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new de.starwit.visionapi.Tracker.TrackedDetection();
    }

    public static de.starwit.visionapi.Tracker.TrackedDetection getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TrackedDetection>
        PARSER = new com.google.protobuf.AbstractParser<TrackedDetection>() {
      @java.lang.Override
      public TrackedDetection parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<TrackedDetection> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TrackedDetection> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public de.starwit.visionapi.Tracker.TrackedDetection getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_visionapi_TrackingOutput_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_visionapi_TrackingOutput_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_visionapi_TrackedDetection_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_visionapi_TrackedDetection_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027visionapi/tracker.proto\022\tvisionapi\032\030vi" +
      "sionapi/detector.proto\032\033visionapi/videos" +
      "ource.proto\"o\n\016TrackingOutput\022$\n\005frame\030\001" +
      " \001(\0132\025.visionapi.VideoFrame\0227\n\022tracked_d" +
      "etections\030\002 \003(\0132\033.visionapi.TrackedDetec" +
      "tion\"N\n\020TrackedDetection\022\'\n\tdetection\030\001 " +
      "\001(\0132\024.visionapi.Detection\022\021\n\tobject_id\030\002" +
      " \001(\014B\026\n\024de.starwit.visionapib\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          de.starwit.visionapi.Detector.getDescriptor(),
          de.starwit.visionapi.Videosource.getDescriptor(),
        });
    internal_static_visionapi_TrackingOutput_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_visionapi_TrackingOutput_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_visionapi_TrackingOutput_descriptor,
        new java.lang.String[] { "Frame", "TrackedDetections", });
    internal_static_visionapi_TrackedDetection_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_visionapi_TrackedDetection_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_visionapi_TrackedDetection_descriptor,
        new java.lang.String[] { "Detection", "ObjectId", });
    de.starwit.visionapi.Detector.getDescriptor();
    de.starwit.visionapi.Videosource.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
