# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: visionapi/aic.proto
# Protobuf Python Version: 5.26.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from visionapi import common_pb2 as visionapi_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13visionapi/aic.proto\x12\tvisionapi\x1a\x16visionapi/common.proto\"i\n\x10\x41iCockpitMessage\x12\x18\n\x10timestamp_utc_ms\x18\x01 \x01(\x04\x12\x11\n\tmedia_url\x18\x02 \x01(\t\x12(\n\nmodel_info\x18\x03 \x01(\x0b\x32\x14.visionapi.ModelInfoB\x16\n\x14\x64\x65.starwit.visionapib\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'visionapi.aic_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\024de.starwit.visionapi'
  _globals['_AICOCKPITMESSAGE']._serialized_start=58
  _globals['_AICOCKPITMESSAGE']._serialized_end=163
# @@protoc_insertion_point(module_scope)
