// This file is generated by rust-protobuf 3.2.0. Do not edit
// .proto file is parsed by protoc 23.0
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `visionapi/messages.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_2_0;

#[derive(PartialEq,Clone,Default,Debug)]
// @@protoc_insertion_point(message:visionapi.VideoFrame)
pub struct VideoFrame {
    // message fields
    // @@protoc_insertion_point(field:visionapi.VideoFrame.source_id)
    pub source_id: ::std::vec::Vec<u8>,
    // @@protoc_insertion_point(field:visionapi.VideoFrame.timestamp_utc_ms)
    pub timestamp_utc_ms: u64,
    // @@protoc_insertion_point(field:visionapi.VideoFrame.shape)
    pub shape: ::protobuf::MessageField<Shape>,
    // @@protoc_insertion_point(field:visionapi.VideoFrame.frame_data)
    pub frame_data: ::std::vec::Vec<u8>,
    // special fields
    // @@protoc_insertion_point(special_field:visionapi.VideoFrame.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a VideoFrame {
    fn default() -> &'a VideoFrame {
        <VideoFrame as ::protobuf::Message>::default_instance()
    }
}

impl VideoFrame {
    pub fn new() -> VideoFrame {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(4);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "source_id",
            |m: &VideoFrame| { &m.source_id },
            |m: &mut VideoFrame| { &mut m.source_id },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "timestamp_utc_ms",
            |m: &VideoFrame| { &m.timestamp_utc_ms },
            |m: &mut VideoFrame| { &mut m.timestamp_utc_ms },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, Shape>(
            "shape",
            |m: &VideoFrame| { &m.shape },
            |m: &mut VideoFrame| { &mut m.shape },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "frame_data",
            |m: &VideoFrame| { &m.frame_data },
            |m: &mut VideoFrame| { &mut m.frame_data },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<VideoFrame>(
            "VideoFrame",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for VideoFrame {
    const NAME: &'static str = "VideoFrame";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.source_id = is.read_bytes()?;
                },
                16 => {
                    self.timestamp_utc_ms = is.read_uint64()?;
                },
                26 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.shape)?;
                },
                34 => {
                    self.frame_data = is.read_bytes()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if !self.source_id.is_empty() {
            my_size += ::protobuf::rt::bytes_size(1, &self.source_id);
        }
        if self.timestamp_utc_ms != 0 {
            my_size += ::protobuf::rt::uint64_size(2, self.timestamp_utc_ms);
        }
        if let Some(v) = self.shape.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if !self.frame_data.is_empty() {
            my_size += ::protobuf::rt::bytes_size(4, &self.frame_data);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if !self.source_id.is_empty() {
            os.write_bytes(1, &self.source_id)?;
        }
        if self.timestamp_utc_ms != 0 {
            os.write_uint64(2, self.timestamp_utc_ms)?;
        }
        if let Some(v) = self.shape.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(3, v, os)?;
        }
        if !self.frame_data.is_empty() {
            os.write_bytes(4, &self.frame_data)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> VideoFrame {
        VideoFrame::new()
    }

    fn clear(&mut self) {
        self.source_id.clear();
        self.timestamp_utc_ms = 0;
        self.shape.clear();
        self.frame_data.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static VideoFrame {
        static instance: VideoFrame = VideoFrame {
            source_id: ::std::vec::Vec::new(),
            timestamp_utc_ms: 0,
            shape: ::protobuf::MessageField::none(),
            frame_data: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for VideoFrame {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("VideoFrame").unwrap()).clone()
    }
}

impl ::std::fmt::Display for VideoFrame {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for VideoFrame {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

#[derive(PartialEq,Clone,Default,Debug)]
// @@protoc_insertion_point(message:visionapi.Shape)
pub struct Shape {
    // message fields
    // @@protoc_insertion_point(field:visionapi.Shape.height)
    pub height: u32,
    // @@protoc_insertion_point(field:visionapi.Shape.width)
    pub width: u32,
    // @@protoc_insertion_point(field:visionapi.Shape.channels)
    pub channels: u32,
    // special fields
    // @@protoc_insertion_point(special_field:visionapi.Shape.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a Shape {
    fn default() -> &'a Shape {
        <Shape as ::protobuf::Message>::default_instance()
    }
}

impl Shape {
    pub fn new() -> Shape {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(3);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "height",
            |m: &Shape| { &m.height },
            |m: &mut Shape| { &mut m.height },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "width",
            |m: &Shape| { &m.width },
            |m: &mut Shape| { &mut m.width },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "channels",
            |m: &Shape| { &m.channels },
            |m: &mut Shape| { &mut m.channels },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<Shape>(
            "Shape",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for Shape {
    const NAME: &'static str = "Shape";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.height = is.read_uint32()?;
                },
                16 => {
                    self.width = is.read_uint32()?;
                },
                24 => {
                    self.channels = is.read_uint32()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.height != 0 {
            my_size += ::protobuf::rt::uint32_size(1, self.height);
        }
        if self.width != 0 {
            my_size += ::protobuf::rt::uint32_size(2, self.width);
        }
        if self.channels != 0 {
            my_size += ::protobuf::rt::uint32_size(3, self.channels);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.height != 0 {
            os.write_uint32(1, self.height)?;
        }
        if self.width != 0 {
            os.write_uint32(2, self.width)?;
        }
        if self.channels != 0 {
            os.write_uint32(3, self.channels)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> Shape {
        Shape::new()
    }

    fn clear(&mut self) {
        self.height = 0;
        self.width = 0;
        self.channels = 0;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static Shape {
        static instance: Shape = Shape {
            height: 0,
            width: 0,
            channels: 0,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for Shape {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("Shape").unwrap()).clone()
    }
}

impl ::std::fmt::Display for Shape {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for Shape {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

#[derive(PartialEq,Clone,Default,Debug)]
// @@protoc_insertion_point(message:visionapi.DetectionOutput)
pub struct DetectionOutput {
    // message fields
    // @@protoc_insertion_point(field:visionapi.DetectionOutput.frame)
    pub frame: ::protobuf::MessageField<VideoFrame>,
    // @@protoc_insertion_point(field:visionapi.DetectionOutput.detections)
    pub detections: ::std::vec::Vec<Detection>,
    // @@protoc_insertion_point(field:visionapi.DetectionOutput.metrics)
    pub metrics: ::protobuf::MessageField<Metrics>,
    // special fields
    // @@protoc_insertion_point(special_field:visionapi.DetectionOutput.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a DetectionOutput {
    fn default() -> &'a DetectionOutput {
        <DetectionOutput as ::protobuf::Message>::default_instance()
    }
}

impl DetectionOutput {
    pub fn new() -> DetectionOutput {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(3);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, VideoFrame>(
            "frame",
            |m: &DetectionOutput| { &m.frame },
            |m: &mut DetectionOutput| { &mut m.frame },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "detections",
            |m: &DetectionOutput| { &m.detections },
            |m: &mut DetectionOutput| { &mut m.detections },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, Metrics>(
            "metrics",
            |m: &DetectionOutput| { &m.metrics },
            |m: &mut DetectionOutput| { &mut m.metrics },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<DetectionOutput>(
            "DetectionOutput",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for DetectionOutput {
    const NAME: &'static str = "DetectionOutput";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.frame)?;
                },
                18 => {
                    self.detections.push(is.read_message()?);
                },
                794 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.metrics)?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.frame.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        for value in &self.detections {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        if let Some(v) = self.metrics.as_ref() {
            let len = v.compute_size();
            my_size += 2 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.frame.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(1, v, os)?;
        }
        for v in &self.detections {
            ::protobuf::rt::write_message_field_with_cached_size(2, v, os)?;
        };
        if let Some(v) = self.metrics.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(99, v, os)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> DetectionOutput {
        DetectionOutput::new()
    }

    fn clear(&mut self) {
        self.frame.clear();
        self.detections.clear();
        self.metrics.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static DetectionOutput {
        static instance: DetectionOutput = DetectionOutput {
            frame: ::protobuf::MessageField::none(),
            detections: ::std::vec::Vec::new(),
            metrics: ::protobuf::MessageField::none(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for DetectionOutput {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("DetectionOutput").unwrap()).clone()
    }
}

impl ::std::fmt::Display for DetectionOutput {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for DetectionOutput {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

#[derive(PartialEq,Clone,Default,Debug)]
// @@protoc_insertion_point(message:visionapi.Detection)
pub struct Detection {
    // message fields
    // @@protoc_insertion_point(field:visionapi.Detection.bounding_box)
    pub bounding_box: ::protobuf::MessageField<BoundingBox>,
    // @@protoc_insertion_point(field:visionapi.Detection.confidence)
    pub confidence: f32,
    // @@protoc_insertion_point(field:visionapi.Detection.class_id)
    pub class_id: u32,
    // special fields
    // @@protoc_insertion_point(special_field:visionapi.Detection.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a Detection {
    fn default() -> &'a Detection {
        <Detection as ::protobuf::Message>::default_instance()
    }
}

impl Detection {
    pub fn new() -> Detection {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(3);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, BoundingBox>(
            "bounding_box",
            |m: &Detection| { &m.bounding_box },
            |m: &mut Detection| { &mut m.bounding_box },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "confidence",
            |m: &Detection| { &m.confidence },
            |m: &mut Detection| { &mut m.confidence },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "class_id",
            |m: &Detection| { &m.class_id },
            |m: &mut Detection| { &mut m.class_id },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<Detection>(
            "Detection",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for Detection {
    const NAME: &'static str = "Detection";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.bounding_box)?;
                },
                21 => {
                    self.confidence = is.read_float()?;
                },
                24 => {
                    self.class_id = is.read_uint32()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.bounding_box.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if self.confidence != 0. {
            my_size += 1 + 4;
        }
        if self.class_id != 0 {
            my_size += ::protobuf::rt::uint32_size(3, self.class_id);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.bounding_box.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(1, v, os)?;
        }
        if self.confidence != 0. {
            os.write_float(2, self.confidence)?;
        }
        if self.class_id != 0 {
            os.write_uint32(3, self.class_id)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> Detection {
        Detection::new()
    }

    fn clear(&mut self) {
        self.bounding_box.clear();
        self.confidence = 0.;
        self.class_id = 0;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static Detection {
        static instance: Detection = Detection {
            bounding_box: ::protobuf::MessageField::none(),
            confidence: 0.,
            class_id: 0,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for Detection {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("Detection").unwrap()).clone()
    }
}

impl ::std::fmt::Display for Detection {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for Detection {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

#[derive(PartialEq,Clone,Default,Debug)]
// @@protoc_insertion_point(message:visionapi.BoundingBox)
pub struct BoundingBox {
    // message fields
    // @@protoc_insertion_point(field:visionapi.BoundingBox.min_x)
    pub min_x: u32,
    // @@protoc_insertion_point(field:visionapi.BoundingBox.min_y)
    pub min_y: u32,
    // @@protoc_insertion_point(field:visionapi.BoundingBox.max_x)
    pub max_x: u32,
    // @@protoc_insertion_point(field:visionapi.BoundingBox.max_y)
    pub max_y: u32,
    // special fields
    // @@protoc_insertion_point(special_field:visionapi.BoundingBox.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a BoundingBox {
    fn default() -> &'a BoundingBox {
        <BoundingBox as ::protobuf::Message>::default_instance()
    }
}

impl BoundingBox {
    pub fn new() -> BoundingBox {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(4);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "min_x",
            |m: &BoundingBox| { &m.min_x },
            |m: &mut BoundingBox| { &mut m.min_x },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "min_y",
            |m: &BoundingBox| { &m.min_y },
            |m: &mut BoundingBox| { &mut m.min_y },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "max_x",
            |m: &BoundingBox| { &m.max_x },
            |m: &mut BoundingBox| { &mut m.max_x },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "max_y",
            |m: &BoundingBox| { &m.max_y },
            |m: &mut BoundingBox| { &mut m.max_y },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<BoundingBox>(
            "BoundingBox",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for BoundingBox {
    const NAME: &'static str = "BoundingBox";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.min_x = is.read_uint32()?;
                },
                16 => {
                    self.min_y = is.read_uint32()?;
                },
                24 => {
                    self.max_x = is.read_uint32()?;
                },
                32 => {
                    self.max_y = is.read_uint32()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.min_x != 0 {
            my_size += ::protobuf::rt::uint32_size(1, self.min_x);
        }
        if self.min_y != 0 {
            my_size += ::protobuf::rt::uint32_size(2, self.min_y);
        }
        if self.max_x != 0 {
            my_size += ::protobuf::rt::uint32_size(3, self.max_x);
        }
        if self.max_y != 0 {
            my_size += ::protobuf::rt::uint32_size(4, self.max_y);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.min_x != 0 {
            os.write_uint32(1, self.min_x)?;
        }
        if self.min_y != 0 {
            os.write_uint32(2, self.min_y)?;
        }
        if self.max_x != 0 {
            os.write_uint32(3, self.max_x)?;
        }
        if self.max_y != 0 {
            os.write_uint32(4, self.max_y)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> BoundingBox {
        BoundingBox::new()
    }

    fn clear(&mut self) {
        self.min_x = 0;
        self.min_y = 0;
        self.max_x = 0;
        self.max_y = 0;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static BoundingBox {
        static instance: BoundingBox = BoundingBox {
            min_x: 0,
            min_y: 0,
            max_x: 0,
            max_y: 0,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for BoundingBox {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("BoundingBox").unwrap()).clone()
    }
}

impl ::std::fmt::Display for BoundingBox {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for BoundingBox {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

#[derive(PartialEq,Clone,Default,Debug)]
// @@protoc_insertion_point(message:visionapi.TrackingOutput)
pub struct TrackingOutput {
    // message fields
    // @@protoc_insertion_point(field:visionapi.TrackingOutput.frame)
    pub frame: ::protobuf::MessageField<VideoFrame>,
    // @@protoc_insertion_point(field:visionapi.TrackingOutput.tracked_detections)
    pub tracked_detections: ::std::vec::Vec<TrackedDetection>,
    // @@protoc_insertion_point(field:visionapi.TrackingOutput.metrics)
    pub metrics: ::protobuf::MessageField<Metrics>,
    // special fields
    // @@protoc_insertion_point(special_field:visionapi.TrackingOutput.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a TrackingOutput {
    fn default() -> &'a TrackingOutput {
        <TrackingOutput as ::protobuf::Message>::default_instance()
    }
}

impl TrackingOutput {
    pub fn new() -> TrackingOutput {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(3);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, VideoFrame>(
            "frame",
            |m: &TrackingOutput| { &m.frame },
            |m: &mut TrackingOutput| { &mut m.frame },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "tracked_detections",
            |m: &TrackingOutput| { &m.tracked_detections },
            |m: &mut TrackingOutput| { &mut m.tracked_detections },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, Metrics>(
            "metrics",
            |m: &TrackingOutput| { &m.metrics },
            |m: &mut TrackingOutput| { &mut m.metrics },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<TrackingOutput>(
            "TrackingOutput",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for TrackingOutput {
    const NAME: &'static str = "TrackingOutput";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.frame)?;
                },
                18 => {
                    self.tracked_detections.push(is.read_message()?);
                },
                794 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.metrics)?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.frame.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        for value in &self.tracked_detections {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        if let Some(v) = self.metrics.as_ref() {
            let len = v.compute_size();
            my_size += 2 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.frame.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(1, v, os)?;
        }
        for v in &self.tracked_detections {
            ::protobuf::rt::write_message_field_with_cached_size(2, v, os)?;
        };
        if let Some(v) = self.metrics.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(99, v, os)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> TrackingOutput {
        TrackingOutput::new()
    }

    fn clear(&mut self) {
        self.frame.clear();
        self.tracked_detections.clear();
        self.metrics.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static TrackingOutput {
        static instance: TrackingOutput = TrackingOutput {
            frame: ::protobuf::MessageField::none(),
            tracked_detections: ::std::vec::Vec::new(),
            metrics: ::protobuf::MessageField::none(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for TrackingOutput {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("TrackingOutput").unwrap()).clone()
    }
}

impl ::std::fmt::Display for TrackingOutput {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for TrackingOutput {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

#[derive(PartialEq,Clone,Default,Debug)]
// @@protoc_insertion_point(message:visionapi.TrackedDetection)
pub struct TrackedDetection {
    // message fields
    // @@protoc_insertion_point(field:visionapi.TrackedDetection.detection)
    pub detection: ::protobuf::MessageField<Detection>,
    // @@protoc_insertion_point(field:visionapi.TrackedDetection.object_id)
    pub object_id: ::std::vec::Vec<u8>,
    // special fields
    // @@protoc_insertion_point(special_field:visionapi.TrackedDetection.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a TrackedDetection {
    fn default() -> &'a TrackedDetection {
        <TrackedDetection as ::protobuf::Message>::default_instance()
    }
}

impl TrackedDetection {
    pub fn new() -> TrackedDetection {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(2);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, Detection>(
            "detection",
            |m: &TrackedDetection| { &m.detection },
            |m: &mut TrackedDetection| { &mut m.detection },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "object_id",
            |m: &TrackedDetection| { &m.object_id },
            |m: &mut TrackedDetection| { &mut m.object_id },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<TrackedDetection>(
            "TrackedDetection",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for TrackedDetection {
    const NAME: &'static str = "TrackedDetection";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.detection)?;
                },
                18 => {
                    self.object_id = is.read_bytes()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.detection.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if !self.object_id.is_empty() {
            my_size += ::protobuf::rt::bytes_size(2, &self.object_id);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.detection.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(1, v, os)?;
        }
        if !self.object_id.is_empty() {
            os.write_bytes(2, &self.object_id)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> TrackedDetection {
        TrackedDetection::new()
    }

    fn clear(&mut self) {
        self.detection.clear();
        self.object_id.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static TrackedDetection {
        static instance: TrackedDetection = TrackedDetection {
            detection: ::protobuf::MessageField::none(),
            object_id: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for TrackedDetection {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("TrackedDetection").unwrap()).clone()
    }
}

impl ::std::fmt::Display for TrackedDetection {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for TrackedDetection {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

#[derive(PartialEq,Clone,Default,Debug)]
// @@protoc_insertion_point(message:visionapi.Metrics)
pub struct Metrics {
    // message fields
    // @@protoc_insertion_point(field:visionapi.Metrics.detection_inference_time_us)
    pub detection_inference_time_us: u32,
    // @@protoc_insertion_point(field:visionapi.Metrics.tracking_inference_time_us)
    pub tracking_inference_time_us: u32,
    // special fields
    // @@protoc_insertion_point(special_field:visionapi.Metrics.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a Metrics {
    fn default() -> &'a Metrics {
        <Metrics as ::protobuf::Message>::default_instance()
    }
}

impl Metrics {
    pub fn new() -> Metrics {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(2);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "detection_inference_time_us",
            |m: &Metrics| { &m.detection_inference_time_us },
            |m: &mut Metrics| { &mut m.detection_inference_time_us },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "tracking_inference_time_us",
            |m: &Metrics| { &m.tracking_inference_time_us },
            |m: &mut Metrics| { &mut m.tracking_inference_time_us },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<Metrics>(
            "Metrics",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for Metrics {
    const NAME: &'static str = "Metrics";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.detection_inference_time_us = is.read_uint32()?;
                },
                16 => {
                    self.tracking_inference_time_us = is.read_uint32()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.detection_inference_time_us != 0 {
            my_size += ::protobuf::rt::uint32_size(1, self.detection_inference_time_us);
        }
        if self.tracking_inference_time_us != 0 {
            my_size += ::protobuf::rt::uint32_size(2, self.tracking_inference_time_us);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.detection_inference_time_us != 0 {
            os.write_uint32(1, self.detection_inference_time_us)?;
        }
        if self.tracking_inference_time_us != 0 {
            os.write_uint32(2, self.tracking_inference_time_us)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> Metrics {
        Metrics::new()
    }

    fn clear(&mut self) {
        self.detection_inference_time_us = 0;
        self.tracking_inference_time_us = 0;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static Metrics {
        static instance: Metrics = Metrics {
            detection_inference_time_us: 0,
            tracking_inference_time_us: 0,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for Metrics {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("Metrics").unwrap()).clone()
    }
}

impl ::std::fmt::Display for Metrics {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for Metrics {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x18visionapi/messages.proto\x12\tvisionapi\"\x9a\x01\n\nVideoFrame\
    \x12\x1b\n\tsource_id\x18\x01\x20\x01(\x0cR\x08sourceId\x12(\n\x10timest\
    amp_utc_ms\x18\x02\x20\x01(\x04R\x0etimestampUtcMs\x12&\n\x05shape\x18\
    \x03\x20\x01(\x0b2\x10.visionapi.ShapeR\x05shape\x12\x1d\n\nframe_data\
    \x18\x04\x20\x01(\x0cR\tframeData\"Q\n\x05Shape\x12\x16\n\x06height\x18\
    \x01\x20\x01(\rR\x06height\x12\x14\n\x05width\x18\x02\x20\x01(\rR\x05wid\
    th\x12\x1a\n\x08channels\x18\x03\x20\x01(\rR\x08channels\"\xa2\x01\n\x0f\
    DetectionOutput\x12+\n\x05frame\x18\x01\x20\x01(\x0b2\x15.visionapi.Vide\
    oFrameR\x05frame\x124\n\ndetections\x18\x02\x20\x03(\x0b2\x14.visionapi.\
    DetectionR\ndetections\x12,\n\x07metrics\x18c\x20\x01(\x0b2\x12.visionap\
    i.MetricsR\x07metrics\"\x81\x01\n\tDetection\x129\n\x0cbounding_box\x18\
    \x01\x20\x01(\x0b2\x16.visionapi.BoundingBoxR\x0bboundingBox\x12\x1e\n\n\
    confidence\x18\x02\x20\x01(\x02R\nconfidence\x12\x19\n\x08class_id\x18\
    \x03\x20\x01(\rR\x07classId\"a\n\x0bBoundingBox\x12\x13\n\x05min_x\x18\
    \x01\x20\x01(\rR\x04minX\x12\x13\n\x05min_y\x18\x02\x20\x01(\rR\x04minY\
    \x12\x13\n\x05max_x\x18\x03\x20\x01(\rR\x04maxX\x12\x13\n\x05max_y\x18\
    \x04\x20\x01(\rR\x04maxY\"\xb7\x01\n\x0eTrackingOutput\x12+\n\x05frame\
    \x18\x01\x20\x01(\x0b2\x15.visionapi.VideoFrameR\x05frame\x12J\n\x12trac\
    ked_detections\x18\x02\x20\x03(\x0b2\x1b.visionapi.TrackedDetectionR\x11\
    trackedDetections\x12,\n\x07metrics\x18c\x20\x01(\x0b2\x12.visionapi.Met\
    ricsR\x07metrics\"c\n\x10TrackedDetection\x122\n\tdetection\x18\x01\x20\
    \x01(\x0b2\x14.visionapi.DetectionR\tdetection\x12\x1b\n\tobject_id\x18\
    \x02\x20\x01(\x0cR\x08objectId\"\x85\x01\n\x07Metrics\x12=\n\x1bdetectio\
    n_inference_time_us\x18\x01\x20\x01(\rR\x18detectionInferenceTimeUs\x12;\
    \n\x1atracking_inference_time_us\x18\x02\x20\x01(\rR\x17trackingInferenc\
    eTimeUsB\x16\n\x14de.starwit.visionapib\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(8);
            messages.push(VideoFrame::generated_message_descriptor_data());
            messages.push(Shape::generated_message_descriptor_data());
            messages.push(DetectionOutput::generated_message_descriptor_data());
            messages.push(Detection::generated_message_descriptor_data());
            messages.push(BoundingBox::generated_message_descriptor_data());
            messages.push(TrackingOutput::generated_message_descriptor_data());
            messages.push(TrackedDetection::generated_message_descriptor_data());
            messages.push(Metrics::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
