name: Java CI

on:
  push:
    branches:
      - main

permissions:
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Build with Maven
        working-directory: java/visionapi
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ github.token }}